import { projectSocialResourceSnapshot } from "./projection";

const organizationId = "11111111-1111-4111-8111-111111111111";
const branchId = "22222222-2222-4222-8222-222222222222";

export function buildDemoSocialResourceSnapshot() {
  return projectSocialResourceSnapshot({
    expectedOrganizationId: organizationId,
    expectedBranchId: branchId,
    demo: true,
    row: {
      organization_id: organizationId,
      branch_id: branchId,
      generated_at: "2026-09-01T10:24:00+08:00",
      item_total: 4,
      effective_total: 2,
      pending_confirmation_total: 1,
      inactive_total: 1,
      expired_total: 1,
      items_truncated: false,
      type_options: ["福利諮詢", "社區支持", "輔具資源"],
      audience_options: ["設籍本市且符合機構公告條件", "日照服務使用者與主要照顧者"],
      type_options_truncated: false,
      audience_options_truncated: false,
      expiry_rule_status: "not_configured",
      confirmation_rule_status: "missing_date_only",
      items: [
        {
          resource_id: "31111111-1111-4111-8111-111111111111",
          reference_year: 2026,
          name: "社區照顧支持窗口",
          resource_type: "社區支持",
          audience_state: "provided",
          audience_detail: "日照服務使用者與主要照顧者",
          eligibility_state: "provided",
          eligibility_detail: "依承辦單位最新公告及人工審查結果辦理",
          contact_state: "provided",
          contact_detail: "合成示例窗口 02-0000-0000",
          validity_state: "open_ended",
          valid_from: "2026-01-01",
          valid_until: null,
          last_confirmed_on: "2026-08-25",
          status: "active",
          row_version: 3,
          updated_at: "2026-08-25T09:20:00+08:00",
          expired: false,
          effective: true,
        },
        {
          resource_id: "31222222-2222-4222-8222-222222222222",
          reference_year: 2026,
          name: "福利資格諮詢服務",
          resource_type: "福利諮詢",
          audience_state: "provided",
          audience_detail: "設籍本市且符合機構公告條件",
          eligibility_state: "missing",
          eligibility_detail: null,
          contact_state: "provided",
          contact_detail: "合成示例承辦窗口；正式資料須人工確認",
          validity_state: "date_range",
          valid_from: "2026-01-01",
          valid_until: "2026-12-31",
          last_confirmed_on: null,
          status: "active",
          row_version: 1,
          updated_at: "2026-08-28T15:10:00+08:00",
          expired: false,
          effective: true,
        },
        {
          resource_id: "31333333-3333-4333-8333-333333333333",
          reference_year: 2025,
          name: "舊年度輔具諮詢",
          resource_type: "輔具資源",
          audience_state: "not_applicable",
          audience_detail: null,
          eligibility_state: "provided",
          eligibility_detail: "依當年度承辦單位書面資料",
          contact_state: "missing",
          contact_detail: null,
          validity_state: "date_range",
          valid_from: "2025-01-01",
          valid_until: "2025-12-31",
          last_confirmed_on: null,
          status: "inactive",
          row_version: 4,
          updated_at: "2026-01-05T11:00:00+08:00",
          expired: true,
          effective: false,
        },
        {
          resource_id: "31444444-4444-4444-8444-444444444444",
          reference_year: 2026,
          name: "待補有效期間的社區據點",
          resource_type: "社區支持",
          audience_state: "missing",
          audience_detail: null,
          eligibility_state: "not_applicable",
          eligibility_detail: null,
          contact_state: "not_applicable",
          contact_detail: null,
          validity_state: "missing",
          valid_from: null,
          valid_until: null,
          last_confirmed_on: "2026-08-30",
          status: "active",
          row_version: 2,
          updated_at: "2026-08-30T08:15:00+08:00",
          expired: false,
          effective: false,
        },
      ],
    },
  });
}
