// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { FormLifecycleAction } from "./form-lifecycle-action";
import type { FormGovernanceVersion } from "@/lib/form-governance/types";
import { hasPendingOperations, tryAcquireViewTransition } from "@/lib/navigation/pending-operation-lock";
const refresh=vi.fn();vi.mock("next/navigation",()=>({useRouter:()=>({refresh})}));
const id="ac000000-0000-4000-8000-000000000001"; const other="ac000000-0000-4000-8000-000000000002";
const version:FormGovernanceVersion={id,definitionId:other,formKey:"tenant.custom.test",name:"合成表單",category:"行政表單",official:false,version:1,status:"published",effectiveFrom:"2026-01-01",effectiveTo:null,schemaFieldCount:1,scoringRuleCount:0,publishedAt:null,contentHash:null,publication:null};
const event={branchId:id,branchName:"合成分支",id:other,formVersionId:id,action:"request_retirement",requestId:null,newVersionId:null,actorId:id,reason:"合成停用原因",effectiveThrough:null,createdAt:"2026-09-22T08:00:00+00:00",byCurrentUser:true};
function envelope(data:unknown,status=200){return new Response(JSON.stringify({requestId:id,status:"ok",data,errors:[]}),{status});}
function history(events:unknown[]=[]){return envelope({history:{formVersionId:id,events,total:events.length,truncated:false},demo:false});}
function saved(replayed=false){return envelope({receipt:{event:{...event,action:"clone",reason:"合成改版原因",newVersionId:other},replayed},persisted:true,demo:false},replayed?200:201);}
beforeAll(()=>{Object.defineProperty(HTMLDialogElement.prototype,"showModal",{configurable:true,value(){this.setAttribute("open","");}});Object.defineProperty(HTMLDialogElement.prototype,"close",{configurable:true,value(){this.removeAttribute("open");}});});
afterEach(()=>{cleanup();refresh.mockReset();vi.unstubAllGlobals();});
async function open(){render(<FormLifecycleAction version={version} instance="desktop" enabled/>);fireEvent.click(screen.getByRole("button",{name:"改版／停用歷程"}));await waitFor(()=>expect(screen.queryByText("正在確認版本操作…")).toBeNull());}
describe("form lifecycle actions",()=>{
 it("demo/disabled never loads or mutates",()=>{const fetch=vi.fn();vi.stubGlobal("fetch",fetch);render(<FormLifecycleAction version={version} instance="desktop" enabled={false}/>);fireEvent.click(screen.getByRole("button",{name:"改版／停用歷程"}));expect(fetch).not.toHaveBeenCalled();});
 it("loads history then clones once without changing original schema",async()=>{const fetch=vi.fn().mockResolvedValueOnce(history()).mockResolvedValueOnce(saved());vi.stubGlobal("fetch",fetch);await open();fireEvent.change(screen.getByLabelText("原因（至少五字）"),{target:{value:"合成改版原因"}});fireEvent.click(screen.getByRole("button",{name:"複製成下一版草稿"}));await waitFor(()=>expect(refresh).toHaveBeenCalledTimes(1));expect(JSON.parse(fetch.mock.calls[1][1].body)).toEqual({action:"clone",formVersionId:id,requestId:null,reason:"合成改版原因"});});
 it("does not expose self-approval",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(history([event])));await open();expect(screen.queryByRole("button",{name:"核准停用"})).toBeNull();expect(screen.getByText("這是您提出的申請，請由另一位管理員覆核。")).toBeTruthy();});
 it("allows independent approval with matching request",async()=>{const fetch=vi.fn().mockResolvedValueOnce(history([{...event,byCurrentUser:false,actorId:other}])).mockResolvedValueOnce(envelope({receipt:{event:{...event,id,action:"approve_retirement",requestId:other,effectiveThrough:"2026-09-22",reason:"合成覆核原因"},replayed:false},persisted:true,demo:false},201));vi.stubGlobal("fetch",fetch);await open();fireEvent.change(screen.getByLabelText("原因（至少五字）"),{target:{value:"合成覆核原因"}});fireEvent.click(screen.getByRole("button",{name:"核准停用"}));await waitFor(()=>expect(refresh).toHaveBeenCalledTimes(1));expect(JSON.parse(fetch.mock.calls[1][1].body).requestId).toBe(other);});
 it("freezes uncertain request/key even when next attempt receives denial",async()=>{const denial=new Response(JSON.stringify({requestId:id,status:"error",data:null,errors:[{code:"DENIED",message:"denied"}]}),{status:403});const fetch=vi.fn().mockResolvedValueOnce(history()).mockRejectedValueOnce(new Error("network")).mockResolvedValueOnce(denial).mockResolvedValueOnce(saved(true));vi.stubGlobal("fetch",fetch);await open();fireEvent.change(screen.getByLabelText("原因（至少五字）"),{target:{value:"合成改版原因"}});fireEvent.click(screen.getByRole("button",{name:"複製成下一版草稿"}));await waitFor(()=>expect(screen.getByRole("button",{name:"以原操作重試"})).toBeTruthy());expect((screen.getByRole("button",{name:"關閉"}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole("button",{name:"以原操作重試"}));await waitFor(()=>expect(fetch).toHaveBeenCalledTimes(3));await waitFor(()=>expect((screen.getByRole("button",{name:"以原操作重試"})as HTMLButtonElement).disabled).toBe(false));expect((screen.getByRole("button",{name:"關閉"})as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole("button",{name:"以原操作重試"}));await waitFor(()=>expect(refresh).toHaveBeenCalledTimes(1));expect(fetch.mock.calls[1][1].body).toBe(fetch.mock.calls[3][1].body);expect(fetch.mock.calls[1][1].headers["Idempotency-Key"]).toBe(fetch.mock.calls[3][1].headers["Idempotency-Key"]);});
 it("blocks writes until history is confirmed",async()=>{const fetch=vi.fn().mockRejectedValue(new Error("offline"));vi.stubGlobal("fetch",fetch);await open();expect((screen.getByRole("button",{name:"複製成下一版草稿"}).closest("fieldset") as HTMLFieldSetElement).disabled).toBe(true);expect(screen.getByRole("button",{name:"重試載入歷程"})).toBeTruthy();});
 it("does not start a write during an existing refresh lease",async()=>{const fetch=vi.fn().mockResolvedValueOnce(history());vi.stubGlobal("fetch",fetch);await open();fireEvent.change(screen.getByLabelText("原因（至少五字）"),{target:{value:"合成改版原因"}});const release=tryAcquireViewTransition();try{fireEvent.click(screen.getByRole("button",{name:"複製成下一版草稿"}));expect(fetch).toHaveBeenCalledTimes(1);expect(hasPendingOperations()).toBe(false);expect(screen.getByText("畫面正在更新或切換分支，請稍候再操作。")).toBeTruthy();}finally{release?.();}});
 it("preserves unresolved lease across unmount until a correlated late success",async()=>{let resolve!:(value:Response)=>void;const pending=new Promise<Response>(r=>{resolve=r;});const fetch=vi.fn().mockResolvedValueOnce(history()).mockReturnValueOnce(pending);vi.stubGlobal("fetch",fetch);await open();fireEvent.change(screen.getByLabelText("原因（至少五字）"),{target:{value:"合成改版原因"}});fireEvent.click(screen.getByRole("button",{name:"複製成下一版草稿"}));expect(hasPendingOperations()).toBe(true);cleanup();expect(hasPendingOperations()).toBe(true);expect(tryAcquireViewTransition()).toBeNull();resolve(saved());await waitFor(()=>expect(hasPendingOperations()).toBe(false));expect(refresh).not.toHaveBeenCalled();});
 it("asks before discarding a typed reason and does not reuse a failed re-open history",async()=>{const fetch=vi.fn().mockResolvedValueOnce(history()).mockRejectedValueOnce(new Error("offline"));vi.stubGlobal("fetch",fetch);const confirm=vi.spyOn(window,"confirm").mockReturnValue(false);try{await open();fireEvent.change(screen.getByLabelText("原因（至少五字）"),{target:{value:"尚未送出改版原因"}});fireEvent.click(screen.getByRole("button",{name:"關閉"}));expect(screen.getByRole("dialog")).toBeTruthy();confirm.mockReturnValue(true);fireEvent.click(screen.getByRole("button",{name:"關閉"}));expect(screen.queryByRole("dialog")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"改版／停用歷程"}));await waitFor(()=>expect(screen.getByRole("button",{name:"重試載入歷程"})).toBeTruthy());expect((screen.getByRole("button",{name:"複製成下一版草稿"}).closest("fieldset")as HTMLFieldSetElement).disabled).toBe(true);}finally{confirm.mockRestore();}});
});
