import { projectAdaptationAssessmentSnapshot } from "./projection";

const ORGANIZATION_ID = "11111111-1111-4111-8111-111111111111";
const BRANCH_ID = "22222222-2222-4222-8222-222222222222";
const ASSESSOR_ID = "32320000-0000-4000-8000-000000000001";

function taipeiDate(value: Date) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(value);
}

function atTaipei(dateValue: string, time: string) {
  return new Date(`${dateValue}T${time}+08:00`).toISOString();
}

function daysFrom(now: Date, amount: number) {
  return taipeiDate(new Date(now.getTime() + amount * 24 * 60 * 60 * 1000));
}

export function buildDemoAdaptationAssessmentSnapshot() {
  const now = new Date();
  const today = taipeiDate(now);
  const prior = daysFrom(now, -8);
  const overdue = daysFrom(now, -2);
  const upcoming = daysFrom(now, 14);
  const generatedAt = now.toISOString();

  return projectAdaptationAssessmentSnapshot({
    expectedOrganizationId: ORGANIZATION_ID,
    expectedBranchId: BRANCH_ID,
    demo: true,
    row: {
      organization_id: ORGANIZATION_ID,
      branch_id: BRANCH_ID,
      generated_at: generatedAt,
      items: [
        {
          client_id: "32000000-0000-4000-8000-000000000001",
          client_display_name: "合成個案 A",
          service_status: "active",
          admitted_on: prior,
          ended_on: null,
          version_id: "32100000-0000-4000-8000-000000000002",
          assessment_key: "32200000-0000-4000-8000-000000000001",
          assessment_version: 2,
          record_state: "signed",
          assessed_on: today,
          adaptation_status: "settled",
          assessment_summary: "合成示例：能辨識日照環境與主要工作人員，並能表達活動偏好。此為人工摘要，不是量表分數或診斷。",
          reassessment_due_on: upcoming,
          reassessment_due: false,
          needs_follow_up: false,
          current_follow_up_status: "not_required",
          form_basis: "manual_unstandardized",
          form_version_reference: "manual-adaptation-v1",
          assessor_user_id: ASSESSOR_ID,
          assessor_display_name: "林社工",
          correction_reason: null,
          signed_at: atTaipei(today, "10:05:00"),
          signer_display_name: "林社工",
          created_at: atTaipei(today, "10:05:00"),
          follow_up_event_id: null,
          follow_up_sequence: 0,
          follow_up_status: null,
          follow_up_due_on: null,
          follow_up_plan: null,
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: null,
          follow_up_committed_at: null,
          follow_up_overdue: false,
          version_history: [
            {
              version_id: "32100000-0000-4000-8000-000000000001",
              assessment_version: 1,
              record_state: "draft",
              assessed_on: today,
              adaptation_status: "settled",
              assessment_summary: "合成示例：能辨識日照環境與主要工作人員，並能表達活動偏好。此為人工摘要，不是量表分數或診斷。",
              reassessment_due_on: upcoming,
              needs_follow_up: false,
              form_basis: "manual_unstandardized",
              form_version_reference: "manual-adaptation-v1",
              correction_reason: null,
              assessor_display_name: "林社工",
              signed_at: null,
              signer_display_name: null,
              created_at: atTaipei(today, "10:00:00"),
            },
            {
              version_id: "32100000-0000-4000-8000-000000000002",
              assessment_version: 2,
              record_state: "signed",
              assessed_on: today,
              adaptation_status: "settled",
              assessment_summary: "合成示例：能辨識日照環境與主要工作人員，並能表達活動偏好。此為人工摘要，不是量表分數或診斷。",
              reassessment_due_on: upcoming,
              needs_follow_up: false,
              form_basis: "manual_unstandardized",
              form_version_reference: "manual-adaptation-v1",
              correction_reason: null,
              assessor_display_name: "林社工",
              signed_at: atTaipei(today, "10:05:00"),
              signer_display_name: "林社工",
              created_at: atTaipei(today, "10:05:00"),
            },
          ],
          version_history_total: 2,
          follow_up_history: [],
          follow_up_history_total: 0,
        },
        {
          client_id: "32000000-0000-4000-8000-000000000002",
          client_display_name: "合成個案 B",
          service_status: "active",
          admitted_on: today,
          ended_on: null,
          version_id: null,
          assessment_key: null,
          assessment_version: null,
          record_state: null,
          assessed_on: null,
          adaptation_status: null,
          assessment_summary: null,
          reassessment_due_on: null,
          reassessment_due: false,
          needs_follow_up: false,
          current_follow_up_status: "not_assessed",
          form_basis: null,
          form_version_reference: null,
          assessor_user_id: null,
          assessor_display_name: null,
          correction_reason: null,
          signed_at: null,
          signer_display_name: null,
          created_at: null,
          follow_up_event_id: null,
          follow_up_sequence: 0,
          follow_up_status: null,
          follow_up_due_on: null,
          follow_up_plan: null,
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: null,
          follow_up_committed_at: null,
          follow_up_overdue: false,
          version_history: [],
          version_history_total: 0,
          follow_up_history: [],
          follow_up_history_total: 0,
        },
        {
          client_id: "32000000-0000-4000-8000-000000000003",
          client_display_name: "合成個案 C",
          service_status: "suspended",
          admitted_on: prior,
          ended_on: null,
          version_id: "32100000-0000-4000-8000-000000000003",
          assessment_key: "32200000-0000-4000-8000-000000000002",
          assessment_version: 1,
          record_state: "draft",
          assessed_on: prior,
          adaptation_status: "adjusting",
          assessment_summary: "合成示例：近期仍在熟悉作息，工作人員記錄到需要較多口頭提示。此為人工觀察摘要。",
          reassessment_due_on: today,
          reassessment_due: true,
          needs_follow_up: true,
          current_follow_up_status: "not_started",
          form_basis: "manual_unstandardized",
          form_version_reference: "manual-adaptation-v1",
          assessor_user_id: ASSESSOR_ID,
          assessor_display_name: "林社工",
          correction_reason: null,
          signed_at: null,
          signer_display_name: null,
          created_at: atTaipei(prior, "14:20:00"),
          follow_up_event_id: null,
          follow_up_sequence: 0,
          follow_up_status: null,
          follow_up_due_on: null,
          follow_up_plan: null,
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: null,
          follow_up_committed_at: null,
          follow_up_overdue: false,
          version_history: [{
            version_id: "32100000-0000-4000-8000-000000000003",
            assessment_version: 1,
            record_state: "draft",
            assessed_on: prior,
            adaptation_status: "adjusting",
            assessment_summary: "合成示例：近期仍在熟悉作息，工作人員記錄到需要較多口頭提示。此為人工觀察摘要。",
            reassessment_due_on: today,
            needs_follow_up: true,
            form_basis: "manual_unstandardized",
            form_version_reference: "manual-adaptation-v1",
            correction_reason: null,
            assessor_display_name: "林社工",
            signed_at: null,
            signer_display_name: null,
            created_at: atTaipei(prior, "14:20:00"),
          }],
          version_history_total: 1,
          follow_up_history: [],
          follow_up_history_total: 0,
        },
        {
          client_id: "32000000-0000-4000-8000-000000000004",
          client_display_name: "合成個案 D",
          service_status: "active",
          admitted_on: prior,
          ended_on: null,
          version_id: "32100000-0000-4000-8000-000000000006",
          assessment_key: "32200000-0000-4000-8000-000000000003",
          assessment_version: 3,
          record_state: "corrected",
          assessed_on: prior,
          adaptation_status: "support_requested",
          assessment_summary: "合成示例：人工評估認為目前需要安排個別支持並持續觀察。內容不代表臨床診斷。",
          reassessment_due_on: overdue,
          reassessment_due: true,
          needs_follow_up: true,
          current_follow_up_status: "pending",
          form_basis: "manual_unstandardized",
          form_version_reference: "manual-adaptation-v1",
          assessor_user_id: ASSESSOR_ID,
          assessor_display_name: "林社工",
          correction_reason: "合成示例：補正人工摘要中的實際觀察描述。",
          signed_at: atTaipei(prior, "11:30:00"),
          signer_display_name: "林社工",
          created_at: atTaipei(prior, "11:30:00"),
          follow_up_event_id: "32400000-0000-4000-8000-000000000001",
          follow_up_sequence: 1,
          follow_up_status: "pending",
          follow_up_due_on: overdue,
          follow_up_plan: "合成示例：與照顧團隊確認下一次支持安排。",
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: "林社工",
          follow_up_committed_at: atTaipei(prior, "11:35:00"),
          follow_up_overdue: true,
          version_history: [
            {
              version_id: "32100000-0000-4000-8000-000000000004",
              assessment_version: 1,
              record_state: "draft",
              assessed_on: prior,
              adaptation_status: "support_requested",
              assessment_summary: "合成示例：人工評估認為目前需要安排支持並持續觀察。",
              reassessment_due_on: overdue,
              needs_follow_up: true,
              form_basis: "manual_unstandardized",
              form_version_reference: "manual-adaptation-v1",
              correction_reason: null,
              assessor_display_name: "林社工",
              signed_at: null,
              signer_display_name: null,
              created_at: atTaipei(prior, "11:00:00"),
            },
            {
              version_id: "32100000-0000-4000-8000-000000000005",
              assessment_version: 2,
              record_state: "signed",
              assessed_on: prior,
              adaptation_status: "support_requested",
              assessment_summary: "合成示例：人工評估認為目前需要安排支持並持續觀察。",
              reassessment_due_on: overdue,
              needs_follow_up: true,
              form_basis: "manual_unstandardized",
              form_version_reference: "manual-adaptation-v1",
              correction_reason: null,
              assessor_display_name: "林社工",
              signed_at: atTaipei(prior, "11:10:00"),
              signer_display_name: "林社工",
              created_at: atTaipei(prior, "11:10:00"),
            },
            {
              version_id: "32100000-0000-4000-8000-000000000006",
              assessment_version: 3,
              record_state: "corrected",
              assessed_on: prior,
              adaptation_status: "support_requested",
              assessment_summary: "合成示例：人工評估認為目前需要安排個別支持並持續觀察。內容不代表臨床診斷。",
              reassessment_due_on: overdue,
              needs_follow_up: true,
              form_basis: "manual_unstandardized",
              form_version_reference: "manual-adaptation-v1",
              correction_reason: "合成示例：補正人工摘要中的實際觀察描述。",
              assessor_display_name: "林社工",
              signed_at: atTaipei(prior, "11:30:00"),
              signer_display_name: "林社工",
              created_at: atTaipei(prior, "11:30:00"),
            },
          ],
          version_history_total: 3,
          follow_up_history: [{
            event_id: "32400000-0000-4000-8000-000000000001",
            sequence: 1,
            follow_up_status: "pending",
            due_on: overdue,
            follow_up_plan: "合成示例：與照顧團隊確認下一次支持安排。",
            follow_up_outcome: null,
            transition_reason: null,
            committer_display_name: "林社工",
            committed_at: atTaipei(prior, "11:35:00"),
          }],
          follow_up_history_total: 1,
        },
      ],
      item_total: 4,
      matching_total: 4,
      items_truncated: false,
      assessed_total: 3,
      not_assessed_total: 1,
      reassessment_due_total: 2,
      needs_follow_up_total: 2,
      open_follow_up_total: 1,
      overdue_follow_up_total: 1,
      draft_total: 1,
      completed_total: 2,
      client_options: [
        { client_id: "32000000-0000-4000-8000-000000000001", display_name: "合成個案 A", service_status: "active", admitted_on: prior, ended_on: null },
        { client_id: "32000000-0000-4000-8000-000000000002", display_name: "合成個案 B", service_status: "active", admitted_on: today, ended_on: null },
        { client_id: "32000000-0000-4000-8000-000000000003", display_name: "合成個案 C", service_status: "suspended", admitted_on: prior, ended_on: null },
        { client_id: "32000000-0000-4000-8000-000000000004", display_name: "合成個案 D", service_status: "active", admitted_on: prior, ended_on: null },
      ],
      client_total: 4,
      client_options_truncated: false,
      assessor_options: [{ user_id: ASSESSOR_ID, display_name: "林社工" }],
      assessor_total: 1,
      assessor_options_truncated: false,
      assessment_method_status: "manual_unstandardized_only",
      form_publication_status: "not_published_not_claimed",
      offline_sync_status: "not_configured",
      follow_up_notification_status: "none_not_sent",
    },
  });
}
