import type { TaipeiForm } from "./catalog";
import type { TaipeiWorkflow } from "./workflow";
export type TaipeiAnswer = { state: "missing" | "not_applicable" | "recorded" | "unconfirmed";
  value: string | number | string[] | null; reason: string | null };
export type TaipeiAnswers = Record<string, TaipeiAnswer>;
export type TaipeiAbcdPrefill = { fieldKey: string; value: string | number | string[]; sourceLabel: string };
export type TaipeiDraft = { id: string; organizationId: string; branchId: string; clientId: string;
  form: TaipeiForm; usageYear: 115; month: number; version: number; previousVersionId: string | null;
  contentHash: string; answers: TaipeiAnswers; sourceSnapshot: TaipeiMonthlySources | null; createdAt: string;
  publicationStatus: "pending_approval"; state: "draft" };
export type TaipeiMeasurementSource = { id: string; measuredAt: string; kind: string; numericValue: number | null;
  textValue: string | null; unit: string | null; recordedBy: string | null };
export type TaipeiCareSource = { id: string; version: number; occurredAt: string; contentHash: string;
  recordedBy: string; data: Record<string, unknown> };
export type TaipeiMonthlySources = { capturedAt: string; measurements: TaipeiMeasurementSource[];
  careRecords: TaipeiCareSource[]; healthAccess: boolean; careAccess: boolean };
export type TaipeiDraftSnapshot = { organizationId: string; branchId: string; clientId: string; form: TaipeiForm;
  usageYear: 115; month: number; latest: TaipeiDraft | null; history: { id: string; version: number; createdAt: string }[];
  currentSources: TaipeiMonthlySources | null; canEdit: boolean; workflow?: TaipeiWorkflow;
  canSubmit?: boolean; canReview?: boolean; canCorrect?: boolean; canExport?: boolean };
export type TaipeiDraftMutation = { client_id: string; form: TaipeiForm; usage_year: 115; month: number;
  template_key: string; source_revision: "114.11"; source_sha256: string;
  expected_version: number; expected_content_hash: string | null; answers: TaipeiAnswers; idempotency_key: string };
