// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { TenantContext } from "@/lib/domain/types";
import { buildDemoReferralManagementSnapshot } from "@/lib/referral-management/demo";
import { clearReferralPendingOnLogout, getReferralPending, observeReferralAuthority, referralAuthoritySignature } from "@/lib/referral-management/pending";
import { hasPendingOperations, hasViewTransition } from "@/lib/navigation/pending-operation-lock";
import type { ReferralManagementFilters, ReferralManagementItem, ReferralManagementSnapshot } from "@/lib/referral-management/types";
import { staffPages } from "@/lib/catalog";
import { ReferralController, ReferralCorrectionForm, ReferralCreateForm, ReferralTransitionForm } from "./referral-actions";
import { ReferralManagementWorkspace } from "./referral-management-workspace";

const mocks = vi.hoisted(() => ({ refresh: vi.fn(), read: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ refresh: mocks.refresh }) }));
vi.mock("@/lib/referral-management/snapshot-client", () => ({ readReferralSnapshot: mocks.read }));
const uuid = (n: number) => `39000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const scope = { organizationId: uuid(80), branchId: uuid(81), userId: uuid(82) };
const filters: ReferralManagementFilters = { clientId: null, receivingUnitMode: "all", receivingUnitCode: null, status: "all", recentFrom: null, recentTo: null, query: "" };
const context: TenantContext = { ...scope, organizationName: "合成機構", branchName: "合成分支", displayName: "合成社工", roles: ["case_manager_social_worker"], scopes: ["clients.read", "referral_management.read", ...["create", "submit", "receive", "respond", "close", "correct"].map((value) => `referral_management.${value}`)], assuranceLevel: "aal2", recentAal2At: null, demo: false };
function snapshot(): ReferralManagementSnapshot { return { ...buildDemoReferralManagementSnapshot({ ...scope, filters }), demo: false, canCreate: true, canSubmit: true, canRegisterReceipt: true, canRespond: true, canClose: true, canCorrect: true }; }
function newer(data: ReferralManagementSnapshot) { const generatedAt = new Date(Date.parse(data.generatedAt) + 1).toISOString(); return { ...data, generatedAt, staleAfter: new Date(Date.parse(generatedAt) + 60_000).toISOString() }; }
function Fixture({ data, actor = context, item = data.items.find((entry) => entry.status === "received")! }: { data: ReferralManagementSnapshot; actor?: TenantContext; item?: ReferralManagementItem }) { return <ReferralController context={actor} filters={filters} snapshot={data}><ReferralCreateForm organizationId={data.organizationId} branchId={data.branchId} canCreate={data.canCreate} clients={data.clientOptions} referenceTime={data.generatedAt}/><ReferralTransitionForm item={item} snapshot={data}/><ReferralTransitionForm item={item} snapshot={data}/><ReferralCorrectionForm item={item} snapshot={data}/></ReferralController>; }
function error(code = "REFERRAL_MANAGEMENT_NOT_AUTHORIZED") { return { requestId: uuid(900), status: "error", data: null, errors: [{ code, message: "合成拒絕" }] }; }
function receipt(body: string, data: ReferralManagementSnapshot) {
  const input = JSON.parse(body); const source = data.items.find((entry) => entry.referralKey === input.referralKey);
  const action = input.action as "create" | "submit" | "register_received" | "respond" | "close" | "correct";
  const kinds = { create: "created", submit: "submitted", register_received: "receipt_registered", respond: "response_recorded", close: "closed", correct: "corrected" };
  const statuses = { create: "draft", submit: "submitted", register_received: "received", respond: "responded", close: "closed", correct: source?.status };
  return { requestId: uuid(901), status: "ok", errors: [], data: { organizationId: scope.organizationId, branchId: scope.branchId, operationId: uuid(200), operationKind: action, referralKey: input.referralKey ?? uuid(300), eventId: uuid(400), eventSequence: (input.expectedSequence ?? 0) + 1, previousEventId: input.previousEventId ?? null, eventKind: kinds[action], referralStatus: statuses[action], receivingUnitState: input.receivingUnitState ?? source!.receivingUnitState, notificationCount: 1, notificationQueueStatus: "queued", notificationProviderStatus: "not_configured", externalDeliveryStatus: "not_configured", deliveryClaim: "no_external_delivery_claim", attachmentStatus: "not_configured", exportStatus: "not_configured", committedAt: new Date().toISOString(), replayed: false, persisted: true, demo: false } };
}
function response(body: unknown, status: number) { return new Response(JSON.stringify(body), { status }); }
async function unknown(data: ReferralManagementSnapshot, action = "登記回覆", verb = "建立登記回覆事件") { fireEvent.click(screen.getAllByRole("button", { name: action })[0]!); fireEvent.change(screen.getByRole("textbox", { name: `${action}內容` }), { target: { value: "合成原操作內容" } }); fireEvent.click(screen.getByRole("button", { name: verb })); await screen.findByText(/原操作結果尚未確認/u); return data; }
beforeEach(() => { mocks.refresh.mockReset(); mocks.read.mockReset(); clearReferralPendingOnLogout(); Object.defineProperty(HTMLDialogElement.prototype, "showModal", { configurable: true, value(this: HTMLDialogElement) { this.open = true; } }); Object.defineProperty(HTMLDialogElement.prototype, "close", { configurable: true, value(this: HTMLDialogElement) { this.open = false; } }); });
afterEach(() => { cleanup(); clearReferralPendingOnLogout(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });

describe("workspace-owned referral writes", () => {
  it("shares one dialog between desktop and mobile triggers and locks unknown content", async () => { const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); render(<Fixture data={data}/>); await unknown(data); expect(screen.getByRole("textbox", { name: "登記回覆內容" })).toBeDisabled(); expect(screen.getAllByRole("button", { name: "登記回覆", hidden: true }).every((button) => (button as HTMLButtonElement).disabled)).toBe(true); expect(document.querySelectorAll("dialog[open]")).toHaveLength(1); expect(hasPendingOperations()).toBe(true); expect(fetch).toHaveBeenCalledTimes(1); });
  it("remounts with the original key/body, does not POST automatically, and retains unknown after403", async () => { const fetch = vi.fn().mockRejectedValueOnce(new Error("lost ACK")).mockResolvedValueOnce(response(error(), 403)).mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); const first = render(<Fixture data={data}/>); await unknown(data); const original = getReferralPending().operation!; first.unmount(); render(<Fixture data={data}/>); expect(fetch).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole("button", { name: "以相同內容重試" })); await waitFor(() => expect(getReferralPending().operation?.phase).toBe("unknown")); expect(getReferralPending().operation?.input.idempotencyKey).toBe(original.input.idempotencyKey); fireEvent.click(screen.getByRole("button", { name: "以相同內容重試" })); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(3)); for (const call of fetch.mock.calls) { expect((call[1] as RequestInit).body).toBe(original.body); expect(((call[1] as RequestInit).headers as Record<string, string>)["idempotency-key"]).toBe(original.input.idempotencyKey); } });
  it("keeps malformed2xx and generic save-failed409 unknown", async () => { const fetch = vi.fn().mockResolvedValueOnce(response({ status: "ok" }, 201)).mockResolvedValueOnce(response(error("REFERRAL_MANAGEMENT_SAVE_FAILED"), 409)); vi.stubGlobal("fetch", fetch); const data = snapshot(); render(<Fixture data={data}/>); await unknown(data); const original = getReferralPending().operation!; fireEvent.click(screen.getByRole("button", { name: "重試同一轉介操作" })); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(2)); expect(getReferralPending().operation?.token).toBe(original.token); expect(hasPendingOperations()).toBe(true); });
  it("releases a known first refusal but keeps entered content in the same dialog", async () => { const fetch = vi.fn().mockResolvedValue(response(error(), 403)); vi.stubGlobal("fetch", fetch); const data = snapshot(); render(<Fixture data={data}/>); fireEvent.click(screen.getAllByRole("button", { name: "登記回覆" })[0]!); fireEvent.change(screen.getByRole("textbox", { name: "登記回覆內容" }), { target: { value: "合成填寫內容" } }); fireEvent.click(screen.getByRole("button", { name: "建立登記回覆事件" })); await screen.findByText(/本次操作未保存/u); expect(getReferralPending().operation).toBeNull(); expect(hasPendingOperations()).toBe(false); expect(screen.getByRole("textbox", { name: "登記回覆內容" })).toHaveValue("合成填寫內容"); });
  it("has no native validation bubbles, focuses the first linked error, and sends nothing", () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); render(<Fixture data={snapshot()}/>); fireEvent.click(screen.getByRole("button", { name: "建立轉介草稿" })); fireEvent.click(screen.getByRole("button", { name: "建立不可變草稿" })); const client = screen.getByRole("combobox", { name: "個案" }); expect(client).toHaveFocus(); expect(client).toHaveAttribute("aria-invalid", "true"); expect(document.getElementById(client.getAttribute("aria-describedby")!)).toHaveTextContent("請選擇目前可服務的個案"); expect(client.closest("form")).toHaveAttribute("novalidate"); expect(fetch).not.toHaveBeenCalled(); });
  it("prevents IME submit and cancel from losing text", () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); render(<Fixture data={snapshot()}/>); fireEvent.click(screen.getAllByRole("button", { name: "登記回覆" })[0]!); const field = screen.getByRole("textbox", { name: "登記回覆內容" }); fireEvent.change(field, { target: { value: "合成未保存內容" } }); fireEvent.compositionStart(field); fireEvent.submit(field.closest("form")!); fireEvent.click(screen.getByRole("button", { name: "取消" })); expect(screen.getByRole("textbox", { name: "登記回覆內容" })).toHaveValue("合成未保存內容"); expect(fetch).not.toHaveBeenCalled(); fireEvent.compositionEnd(field); fireEvent.click(screen.getByRole("button", { name: "取消" })); expect(screen.getByRole("dialog", { name: "放棄未保存的轉介填寫？" })).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "繼續填寫" })); expect(screen.getByRole("textbox", { name: "登記回覆內容" })).toHaveValue("合成未保存內容"); });
  it("suppresses a late success after capability revoke/restore ABA", async () => { let resolve!: (value: Response) => void; const fetch = vi.fn().mockImplementation(() => new Promise<Response>((done) => { resolve = done; })); vi.stubGlobal("fetch", fetch); const data = snapshot(); const ui = render(<Fixture data={data}/>); fireEvent.click(screen.getAllByRole("button", { name: "登記回覆" })[0]!); fireEvent.change(screen.getByRole("textbox", { name: "登記回覆內容" }), { target: { value: "合成原操作內容" } }); fireEvent.click(screen.getByRole("button", { name: "建立登記回覆事件" })); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(1)); const original = getReferralPending().operation!; ui.rerender(<Fixture data={{ ...data, canRespond: false }}/>); ui.rerender(<Fixture data={data}/>); await act(async () => resolve(response(receipt(original.body, data), 201))); expect(getReferralPending().operation?.phase).toBe("unknown"); expect(getReferralPending().operation?.body).toBe(original.body); expect(mocks.refresh).not.toHaveBeenCalled(); expect(screen.queryByText(/操作已保存/u)).not.toBeInTheDocument(); });
  it("redacts retained actor snapshots across A→B→A until a newer generation", () => { const data = snapshot(); const page = staffPages.find((entry) => entry.number === 39)!; const ui = render(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={data} loadError={false}/>); const narrative = data.items[0]!.referralReason; expect(screen.getAllByText(narrative).length).toBeGreaterThan(0); ui.rerender(<ReferralManagementWorkspace context={{ ...context, userId: uuid(83) }} filters={filters} page={page} snapshot={data} loadError={false}/>); expect(screen.queryByText(narrative)).not.toBeInTheDocument(); ui.rerender(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={data} loadError={false}/>); expect(screen.queryByText(narrative)).not.toBeInTheDocument(); ui.rerender(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={newer(data)} loadError={false}/>); expect(screen.getAllByText(narrative).length).toBeGreaterThan(0); });
  it("redacts read-scope revoke/restore while preserving read after manage-only removal", () => { const data = snapshot(); const page = staffPages.find((entry) => entry.number === 39)!; const props = { filters, page, snapshot: data, loadError: false }; const ui = render(<ReferralManagementWorkspace {...props} context={context}/>); const narrative = data.items[0]!.referralReason; ui.rerender(<ReferralManagementWorkspace {...props} context={{ ...context, scopes: context.scopes.filter((scope) => scope !== "referral_management.respond") }}/>); expect(screen.getAllByText(narrative).length).toBeGreaterThan(0); ui.rerender(<ReferralManagementWorkspace {...props} context={{ ...context, scopes: context.scopes.filter((scope) => scope !== "referral_management.read") }}/>); expect(screen.queryByText(narrative)).not.toBeInTheDocument(); ui.rerender(<ReferralManagementWorkspace {...props} context={context}/>); expect(screen.queryByText(narrative)).not.toBeInTheDocument(); });
  it("does not rebase an open editor onto a changed source event", () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); const data = snapshot(); const item = data.items.find((entry) => entry.status === "received")!; const ui = render(<Fixture data={data}/>); fireEvent.click(screen.getAllByRole("button", { name: "登記回覆" })[0]!); fireEvent.change(screen.getByRole("textbox", { name: "登記回覆內容" }), { target: { value: "合成原操作內容" } }); ui.rerender(<Fixture data={newer(data)} item={{ ...item, eventId: uuid(999) }}/>); fireEvent.click(screen.getByRole("button", { name: "建立登記回覆事件" })); expect(screen.getByRole("alert")).toHaveTextContent("畫面版本或授權已更新"); expect(fetch).not.toHaveBeenCalled(); });
  it("keeps success distinct from list update, locks the same chain and restores focus", async () => { const data = snapshot(); const fetch = vi.fn().mockImplementation((_url, init) => Promise.resolve(response(receipt(init.body, data), 201))); vi.stubGlobal("fetch", fetch); render(<Fixture data={data}/>); const trigger = screen.getAllByRole("button", { name: "登記回覆" })[0]!; trigger.focus(); fireEvent.click(trigger); fireEvent.change(screen.getByRole("textbox", { name: "登記回覆內容" }), { target: { value: "合成回覆內容" } }); fireEvent.click(screen.getByRole("button", { name: "建立登記回覆事件" })); await screen.findByText(/清單尚未確認更新/u); expect(getReferralPending().confirmed).toHaveLength(1); expect(screen.queryByText(/清單已確認更新/u)).not.toBeInTheDocument(); expect(screen.getAllByRole("button", { name: "登記回覆" }).every((button) => (button as HTMLButtonElement).disabled)).toBe(true); expect(screen.getByRole("region", { name: "轉介操作回查" })).toHaveFocus(); });
  it("read-only recovery preserves original key/body and does not POST on returned snapshot", async () => { const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); const ui = render(<Fixture data={data}/>); await unknown(data); fireEvent.click(screen.getByRole("button", { name: "回待確認清單" })); const original = getReferralPending().operation!; ui.rerender(<Fixture data={data} actor={{ ...context, userId: uuid(83) }}/>); ui.rerender(<Fixture data={data}/>); expect(screen.queryByText("合成原操作內容")).not.toBeInTheDocument(); mocks.read.mockResolvedValue(newer(data)); fireEvent.click(screen.getByRole("button", { name: "重新核對原範圍授權" })); await waitFor(() => expect(screen.getByRole("button", { name: "以相同內容重試" })).toBeEnabled()); expect(mocks.read).toHaveBeenCalledTimes(1); expect(mocks.read.mock.calls[0]![0]).toEqual(scope); expect(fetch).toHaveBeenCalledTimes(1); expect(getReferralPending().operation?.body).toBe(original.body); expect(getReferralPending().operation?.input.idempotencyKey).toBe(original.input.idempotencyKey); expect(hasPendingOperations()).toBe(true); fireEvent.click(screen.getByRole("button", { name: "以相同內容重試" })); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(2)); expect((fetch.mock.calls[1]![1] as RequestInit).body).toBe(original.body); });
  it("rejects late recovery GET after capability ABA", async () => { const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); let resolve!: (value: ReferralManagementSnapshot) => void; mocks.read.mockImplementation(() => new Promise((done) => { resolve = done; })); const ui = render(<Fixture data={data}/>); await unknown(data); fireEvent.click(screen.getByRole("button", { name: "回待確認清單" })); fireEvent.click(screen.getByRole("button", { name: "重新核對原範圍授權" })); ui.rerender(<Fixture data={{ ...data, canRespond: false }}/>); ui.rerender(<Fixture data={data}/>); await act(async () => resolve(newer(data))); expect(getReferralPending().operation?.phase).toBe("unknown"); expect(fetch).toHaveBeenCalledTimes(1); expect(screen.queryByText(/已確認更新/u)).not.toBeInTheDocument(); });
  it("keeps all standalone triggers disabled without the workspace controller", () => { const data = snapshot(); const item = data.items[0]!; render(<><ReferralCreateForm organizationId={scope.organizationId} branchId={scope.branchId} clients={data.clientOptions} canCreate referenceTime={data.generatedAt}/><ReferralTransitionForm item={item} snapshot={data}/><ReferralCorrectionForm item={item} snapshot={data}/></>); expect(screen.getAllByRole("button").every((button) => (button as HTMLButtonElement).disabled)).toBe(true); });
  it.each(["submitted", "received", "responded"] as const)("preserves the %s transition payload and requires explicit confirmation", async (status) => { const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); const item = data.items.find((entry) => entry.status === status)!; render(<Fixture data={data} item={item}/>); const action = status === "submitted" ? "人工登記收件" : status === "received" ? "登記回覆" : "結案"; await unknown(data, action, `建立${action}事件`); const body = JSON.parse(getReferralPending().operation!.body); expect(body.referralKey).toBe(item.referralKey); expect(body.previousEventId).toBe(item.eventId); expect(body.expectedSequence).toBe(item.sequence); expect(fetch).toHaveBeenCalledTimes(1); });
  it("preserves correction history binding and keeps original current status", async () => { const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); const item = data.items.find((entry) => entry.status === "closed")!; render(<Fixture data={data} item={item}/>); fireEvent.click(screen.getByRole("button", { name: "狹義更正" })); fireEvent.change(screen.getByRole("combobox", { name: "更正哪一事件" }), { target: { value: item.history.at(-1)!.eventId } }); fireEvent.change(screen.getByRole("textbox", { name: "更正後內容" }), { target: { value: "合成更正內容" } }); fireEvent.change(screen.getByRole("textbox", { name: "更正理由" }), { target: { value: "合成更正理由" } }); expect(fetch).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "建立更正事件" })); await screen.findByText(/原操作結果尚未確認/u); expect(getReferralPending().operation?.target?.status).toBe("closed"); expect(JSON.parse(getReferralPending().operation!.body)).toMatchObject({ correctsEventId: item.history.at(-1)!.eventId, previousEventId: item.eventId }); });
  it("acquires the shared read-transition lease before refresh and blocks writes while reading", async () => { let resolve!: () => void; mocks.refresh.mockImplementation(() => new Promise<void>((done) => { resolve = done; })); const data = snapshot(); const fetch = vi.fn().mockImplementation((_url, init) => Promise.resolve(response(receipt(init.body, data), 201))); vi.stubGlobal("fetch", fetch); render(<Fixture data={data}/>); fireEvent.click(screen.getAllByRole("button", { name: "登記回覆" })[0]!); fireEvent.change(screen.getByRole("textbox", { name: "登記回覆內容" }), { target: { value: "合成回覆內容" } }); fireEvent.click(screen.getByRole("button", { name: "建立登記回覆事件" })); await waitFor(() => expect(mocks.refresh).toHaveBeenCalledTimes(1)); expect(hasViewTransition()).toBe(true); expect(screen.getByRole("button", { name: "建立轉介草稿" })).toBeDisabled(); await act(async () => resolve()); expect(hasViewTransition()).toBe(false); });
  it("retains the global privacy generation floor through actual unmount and authority ABA", () => {
    const data = snapshot(); const page = staffPages.find((entry) => entry.number === 39)!;
    const first = render(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={data} loadError={false}/>); first.unmount();
    observeReferralAuthority(referralAuthoritySignature({ ...context, userId: uuid(83) })); observeReferralAuthority(referralAuthoritySignature(context));
    const second = render(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={data} loadError={false}/>);
    expect(screen.queryByText(data.items[0]!.referralReason)).not.toBeInTheDocument();
    second.rerender(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={newer(data)} loadError={false}/>);
    expect(screen.getAllByText(data.items[0]!.referralReason).length).toBeGreaterThan(0);
  });
  it("does not reveal a regressed server generation after the privacy floor clears and remounts", () => {
    const data = snapshot(); const page = staffPages.find((entry) => entry.number === 39)!;
    const first = render(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={data} loadError={false}/>); first.unmount();
    observeReferralAuthority(referralAuthoritySignature({ ...context, userId: uuid(83) })); observeReferralAuthority(referralAuthoritySignature(context));
    const fresh = newer(data); const second = render(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={fresh} loadError={false}/>);
    expect(screen.getAllByText(data.items[0]!.referralReason).length).toBeGreaterThan(0); expect(getReferralPending().snapshotFloor).toBeNull(); second.unmount();
    const third = render(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={data} loadError={false}/>);
    expect(screen.queryByText(data.items[0]!.referralReason)).not.toBeInTheDocument(); third.rerender(<ReferralManagementWorkspace context={context} filters={filters} page={page} snapshot={fresh} loadError={false}/>);
    expect(screen.getAllByText(data.items[0]!.referralReason).length).toBeGreaterThan(0);
  });
  it("shows failed recovery reads outside the closed editor without clearing the write", async () => {
    const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); render(<Fixture data={data}/>); await unknown(data);
    fireEvent.click(screen.getByRole("button", { name: "回待確認清單" })); const original = getReferralPending().operation!; mocks.read.mockRejectedValue(new Error("synthetic403"));
    fireEvent.click(screen.getByRole("button", { name: "重新核對原範圍授權" })); await screen.findByRole("alert");
    expect(screen.getByRole("alert")).toHaveTextContent("未能重新取得授權資料"); expect(getReferralPending().operation?.body).toBe(original.body); expect(hasPendingOperations()).toBe(true); expect(fetch).toHaveBeenCalledTimes(1);
  });
  it.each(["logout", "unmount"] as const)("rejects a late recovery read after %s", async (boundary) => {
    const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); let resolve!: (value: ReferralManagementSnapshot) => void;
    mocks.read.mockImplementation(() => new Promise((done) => { resolve = done; })); const ui = render(<Fixture data={data}/>); await unknown(data); fireEvent.click(screen.getByRole("button", { name: "回待確認清單" })); fireEvent.click(screen.getByRole("button", { name: "重新核對原範圍授權" }));
    if (boundary === "logout") act(clearReferralPendingOnLogout); else ui.unmount();
    await act(async () => resolve(newer(data))); expect(fetch).toHaveBeenCalledTimes(1); expect(screen.queryByText(/已確認更新/u)).not.toBeInTheDocument(); if (boundary === "logout") expect(getReferralPending().operation).toBeNull();
  });
  it("accepts only positive exact same-chain event history as list-update evidence", async () => {
    const data = snapshot(); let saved!: ReturnType<typeof receipt>; const fetch = vi.fn().mockImplementation((_url, init) => { saved = receipt(init.body, data); return Promise.resolve(response(saved, 201)); }); vi.stubGlobal("fetch", fetch); const ui = render(<Fixture data={data}/>);
    fireEvent.click(screen.getAllByRole("button", { name: "登記回覆" })[0]!); fireEvent.change(screen.getByRole("textbox", { name: "登記回覆內容" }), { target: { value: "合成回覆內容" } }); fireEvent.click(screen.getByRole("button", { name: "建立登記回覆事件" })); await screen.findByText(/清單尚未確認更新/u);
    const old = data.items.find((item) => item.referralKey === saved.data.referralKey)!; const current: ReferralManagementItem = { ...old, eventId: saved.data.eventId, sequence: saved.data.eventSequence, previousEventId: old.eventId, eventKind: "response_recorded", status: "responded", occurredAt: saved.data.committedAt, entryContent: "合成回覆內容", history: [{ ...old.history[0]!, eventId: saved.data.eventId, sequence: saved.data.eventSequence, eventKind: "response_recorded", status: "responded", occurredAt: saved.data.committedAt, entryContent: "合成回覆內容" }, ...old.history] };
    const generatedAt = new Date(Math.max(Date.now(), Date.parse(saved.data.committedAt), Date.parse(data.generatedAt) + 1)).toISOString(); const fresh = { ...data, generatedAt, staleAfter: new Date(Date.parse(generatedAt) + 60_000).toISOString(), items: data.items.map((item) => item.referralKey === current.referralKey ? current : item), metrics: { ...data.metrics, received: data.metrics.received - 1, responded: data.metrics.responded + 1 } };
    ui.rerender(<Fixture data={fresh} item={current}/>); await screen.findByText(/清單已確認更新/u); expect(getReferralPending().confirmed).toHaveLength(0); expect(screen.queryByText(/清單尚未確認更新/u)).not.toBeInTheDocument();
  });
  it.each(["missing", "not_applicable", "manual_unstandardized"] as const)("creates an explicit %s unit draft without inventing a unit", async (state) => {
    const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const data = snapshot(); render(<Fixture data={data}/>); fireEvent.click(screen.getByRole("button", { name: "建立轉介草稿" })); fireEvent.change(screen.getByRole("combobox", { name: "個案" }), { target: { value: data.clientOptions[0]!.clientId } }); fireEvent.change(screen.getByRole("combobox", { name: "接收單位狀態" }), { target: { value: state } });
    if (state === "manual_unstandardized") { fireEvent.change(screen.getByRole("textbox", { name: "人工接收單位代碼" }), { target: { value: "SYNTHETIC" } }); fireEvent.change(screen.getByRole("textbox", { name: "人工接收單位名稱" }), { target: { value: "合成院所" } }); }
    fireEvent.change(screen.getByRole("textbox", { name: "轉介原因" }), { target: { value: "合成轉介原因" } }); fireEvent.click(screen.getByRole("button", { name: "建立不可變草稿" })); await screen.findByText(/原操作結果尚未確認/u); const body = JSON.parse(getReferralPending().operation!.body); expect(body.receivingUnitState).toBe(state); expect(body.receivingUnitCode).toBe(state === "manual_unstandardized" ? "SYNTHETIC" : null); expect(body.referralDate).toBe(new Date(`${data.generatedAt.slice(0, 16)}:00Z`).toISOString()); expect(fetch).toHaveBeenCalledTimes(1);
  });
  it("permits a ready internal submit with no optional note but disables missing-unit submit", async () => {
    const fetch = vi.fn().mockRejectedValue(new Error("lost ACK")); vi.stubGlobal("fetch", fetch); const original = snapshot(); const submitted = original.items.find((entry) => entry.status === "submitted")!; const created = submitted.history.at(-1)!;
    const item: ReferralManagementItem = { ...submitted, eventId: created.eventId, sequence: created.sequence, previousEventId: null, eventKind: "created", status: "draft", occurredAt: created.occurredAt, entryContent: null, contentHash: created.contentHash, history: [created] };
    const data = { ...original, items: original.items.map((entry) => entry.referralKey === item.referralKey ? item : entry), metrics: { ...original.metrics, draft: original.metrics.draft + 1, submitted: original.metrics.submitted - 1 } };
    const ui = render(<Fixture data={data} item={{ ...item, receivingUnitState: "missing" }}/>); expect(screen.getAllByRole("button", { name: "送出院內版本" }).every((button) => (button as HTMLButtonElement).disabled)).toBe(true); ui.rerender(<Fixture data={data} item={item}/>); fireEvent.click(screen.getAllByRole("button", { name: "送出院內版本" })[0]!); fireEvent.click(screen.getByRole("button", { name: "建立送出院內版本事件" })); await screen.findByText(/原操作結果尚未確認/u); expect(JSON.parse(getReferralPending().operation!.body)).not.toHaveProperty("entryContent");
  });
});
