import { projectSocialWorkRecordSnapshot } from "./projection";

const ORGANIZATION_ID = "11111111-1111-4111-8111-111111111111";
const BRANCH_ID = "22222222-2222-4222-8222-222222222222";
const AUTHOR_ID = "33333333-3333-4333-8333-333333333333";

function taipeiDate(value: Date) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(value);
}

function atTaipei(dateValue: string, time: string) {
  return new Date(`${dateValue}T${time}+08:00`).toISOString();
}

export function buildDemoSocialWorkRecordSnapshot() {
  const now = new Date();
  const today = taipeiDate(now);
  const prior = taipeiDate(new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000));
  const overdue = taipeiDate(new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000));
  const due = taipeiDate(new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000));
  const generatedAt = now.toISOString();
  const generatedMonth = today.slice(0, 7);
  const currentMonthTotal = [today, prior, prior]
    .filter((value) => value.slice(0, 7) === generatedMonth).length;

  return projectSocialWorkRecordSnapshot({
    expectedOrganizationId: ORGANIZATION_ID,
    expectedBranchId: BRANCH_ID,
    demo: true,
    row: {
      organization_id: ORGANIZATION_ID,
      branch_id: BRANCH_ID,
      generated_at: generatedAt,
      records: [
        {
          record_key: "29000000-0000-4000-8000-000000000001",
          version_id: "29010000-0000-4000-8000-000000000002",
          record_version: 2,
          record_state: "signed",
          client_id: "29020000-0000-4000-8000-000000000001",
          client_display_name: "日照個案甲",
          occurred_at: atTaipei(today, "09:20:00"),
          service_type: "個別會談",
          service_content: "合成示例：討論近期參與活動的感受與可接受的支持方式。",
          service_result: "合成示例：個案能表達偏好，並同意後續由社工再次關懷。",
          author_user_id: AUTHOR_ID,
          author_display_name: "林社工",
          correction_reason: null,
          signed_at: atTaipei(today, "10:05:00"),
          signer_display_name: "林社工",
          created_at: atTaipei(today, "10:05:00"),
          follow_up_event_id: "29030000-0000-4000-8000-000000000001",
          follow_up_sequence: 1,
          follow_up_status: "pending",
          follow_up_due_on: due,
          follow_up_plan: "合成示例：下次服務日確認活動適應情形。",
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: "林社工",
          follow_up_committed_at: atTaipei(today, "10:08:00"),
          follow_up_overdue: false,
          version_history: [
            {
              version_id: "29010000-0000-4000-8000-000000000001",
              record_version: 1,
              record_state: "draft",
              occurred_at: atTaipei(today, "09:20:00"),
              service_type: "個別會談",
              service_content: "合成示例：討論近期參與活動的感受與可接受的支持方式。",
              service_result: "合成示例：個案能表達偏好，並同意後續由社工再次關懷。",
              correction_reason: null,
              author_display_name: "林社工",
              signed_at: null,
              signer_display_name: null,
              created_at: atTaipei(today, "10:00:00"),
            },
            {
              version_id: "29010000-0000-4000-8000-000000000002",
              record_version: 2,
              record_state: "signed",
              occurred_at: atTaipei(today, "09:20:00"),
              service_type: "個別會談",
              service_content: "合成示例：討論近期參與活動的感受與可接受的支持方式。",
              service_result: "合成示例：個案能表達偏好，並同意後續由社工再次關懷。",
              correction_reason: null,
              author_display_name: "林社工",
              signed_at: atTaipei(today, "10:05:00"),
              signer_display_name: "林社工",
              created_at: atTaipei(today, "10:05:00"),
            },
          ],
          version_history_total: 2,
          follow_up_history: [{
            event_id: "29030000-0000-4000-8000-000000000001",
            sequence: 1,
            follow_up_status: "pending",
            due_on: due,
            follow_up_plan: "合成示例：下次服務日確認活動適應情形。",
            follow_up_outcome: null,
            transition_reason: null,
            committer_display_name: "林社工",
            committed_at: atTaipei(today, "10:08:00"),
          }],
          follow_up_history_total: 1,
        },
        {
          record_key: "29000000-0000-4000-8000-000000000002",
          version_id: "29010000-0000-4000-8000-000000000003",
          record_version: 1,
          record_state: "draft",
          client_id: "29020000-0000-4000-8000-000000000002",
          client_display_name: "日照個案乙",
          occurred_at: atTaipei(prior, "14:10:00"),
          service_type: "家屬聯繫",
          service_content: "合成示例：以電話確認家屬近期可聯繫時段。",
          service_result: "合成示例：已約定下次聯繫時間，內容仍待覆核簽署。",
          author_user_id: AUTHOR_ID,
          author_display_name: "林社工",
          correction_reason: null,
          signed_at: null,
          signer_display_name: null,
          created_at: atTaipei(prior, "14:25:00"),
          follow_up_event_id: null,
          follow_up_sequence: 0,
          follow_up_status: null,
          follow_up_due_on: null,
          follow_up_plan: null,
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: null,
          follow_up_committed_at: null,
          follow_up_overdue: false,
          version_history: [{
            version_id: "29010000-0000-4000-8000-000000000003",
            record_version: 1,
            record_state: "draft",
            occurred_at: atTaipei(prior, "14:10:00"),
            service_type: "家屬聯繫",
            service_content: "合成示例：以電話確認家屬近期可聯繫時段。",
            service_result: "合成示例：已約定下次聯繫時間，內容仍待覆核簽署。",
            correction_reason: null,
            author_display_name: "林社工",
            signed_at: null,
            signer_display_name: null,
            created_at: atTaipei(prior, "14:25:00"),
          }],
          version_history_total: 1,
          follow_up_history: [],
          follow_up_history_total: 0,
        },
        {
          record_key: "29000000-0000-4000-8000-000000000003",
          version_id: "29010000-0000-4000-8000-000000000006",
          record_version: 3,
          record_state: "corrected",
          client_id: "29020000-0000-4000-8000-000000000003",
          client_display_name: "日照個案丙",
          occurred_at: atTaipei(prior, "10:30:00"),
          service_type: "資源連結",
          service_content: "合成示例：說明可洽詢的社區支持資源與人工確認流程。",
          service_result: "合成示例：個案表示將與關係人討論後回覆。",
          author_user_id: AUTHOR_ID,
          author_display_name: "林社工",
          correction_reason: "合成示例：修正實際發生時間。",
          signed_at: atTaipei(prior, "11:20:00"),
          signer_display_name: "林社工",
          created_at: atTaipei(prior, "11:20:00"),
          follow_up_event_id: "29030000-0000-4000-8000-000000000002",
          follow_up_sequence: 1,
          follow_up_status: "pending",
          follow_up_due_on: overdue,
          follow_up_plan: "合成示例：確認是否需要協助提出資源申請。",
          follow_up_outcome: null,
          follow_up_transition_reason: null,
          follow_up_committer_display_name: "林社工",
          follow_up_committed_at: atTaipei(prior, "11:25:00"),
          follow_up_overdue: true,
          version_history: [
            {
              version_id: "29010000-0000-4000-8000-000000000004",
              record_version: 1,
              record_state: "draft",
              occurred_at: atTaipei(prior, "10:00:00"),
              service_type: "資源連結",
              service_content: "合成示例：說明可洽詢的社區支持資源與人工確認流程。",
              service_result: "合成示例：個案表示將與關係人討論後回覆。",
              correction_reason: null,
              author_display_name: "林社工",
              signed_at: null,
              signer_display_name: null,
              created_at: atTaipei(prior, "11:00:00"),
            },
            {
              version_id: "29010000-0000-4000-8000-000000000005",
              record_version: 2,
              record_state: "signed",
              occurred_at: atTaipei(prior, "10:00:00"),
              service_type: "資源連結",
              service_content: "合成示例：說明可洽詢的社區支持資源與人工確認流程。",
              service_result: "合成示例：個案表示將與關係人討論後回覆。",
              correction_reason: null,
              author_display_name: "林社工",
              signed_at: atTaipei(prior, "11:05:00"),
              signer_display_name: "林社工",
              created_at: atTaipei(prior, "11:05:00"),
            },
            {
              version_id: "29010000-0000-4000-8000-000000000006",
              record_version: 3,
              record_state: "corrected",
              occurred_at: atTaipei(prior, "10:30:00"),
              service_type: "資源連結",
              service_content: "合成示例：說明可洽詢的社區支持資源與人工確認流程。",
              service_result: "合成示例：個案表示將與關係人討論後回覆。",
              correction_reason: "合成示例：修正實際發生時間。",
              author_display_name: "林社工",
              signed_at: atTaipei(prior, "11:20:00"),
              signer_display_name: "林社工",
              created_at: atTaipei(prior, "11:20:00"),
            },
          ],
          version_history_total: 3,
          follow_up_history: [{
            event_id: "29030000-0000-4000-8000-000000000002",
            sequence: 1,
            follow_up_status: "pending",
            due_on: overdue,
            follow_up_plan: "合成示例：確認是否需要協助提出資源申請。",
            follow_up_outcome: null,
            transition_reason: null,
            committer_display_name: "林社工",
            committed_at: atTaipei(prior, "11:25:00"),
          }],
          follow_up_history_total: 1,
        },
      ],
      record_total: 3,
      matching_total: 3,
      records_truncated: false,
      current_month_total: currentMonthTotal,
      pending_follow_up_total: 2,
      overdue_follow_up_total: 1,
      draft_total: 1,
      signed_total: 2,
      client_options: [
        { client_id: "29020000-0000-4000-8000-000000000001", display_name: "日照個案甲", client_status: "active", admitted_on: prior, ended_on: null },
        { client_id: "29020000-0000-4000-8000-000000000002", display_name: "日照個案乙", client_status: "active", admitted_on: prior, ended_on: null },
        { client_id: "29020000-0000-4000-8000-000000000003", display_name: "日照個案丙", client_status: "active", admitted_on: prior, ended_on: null },
      ],
      client_total: 3,
      client_options_truncated: false,
      service_type_options: ["個別會談", "家屬聯繫", "資源連結"],
      service_type_total: 3,
      service_type_options_truncated: false,
      author_options: [{ user_id: AUTHOR_ID, display_name: "林社工" }],
      author_total: 1,
      author_options_truncated: false,
      offline_sync_status: "not_configured",
      follow_up_notification_status: "none_not_sent",
    },
  });
}
