// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { hasPendingOperations, tryAcquirePendingOperation, tryAcquireViewTransition } from "@/lib/navigation/pending-operation-lock";
import { beginSocialWork, clearSocialWorkPendingOnLogout, getSocialWorkPending, getSocialWorkSnapshotAdmission, isConfirmedSocialWorkRejection, observeSocialWorkAuthority, observeSocialWorkSnapshot, reconcileSocialWorkConfirmed, retrySocialWork, settleSocialWork, socialWorkAuthoritySignature, socialWorkRequestBody } from "./pending";
import { normalizeSocialWorkSnapshot } from "./snapshot-contract";
import { swFixture, swFresh, swInput, swSuccess, swUuid } from "./pending-fixtures.test-helper";

let serial = 0; let fixture: ReturnType<typeof swFixture>; let external: (() => void) | null = null;
const guardFault = vi.hoisted(() => ({ fail: false }));
vi.mock("@/lib/navigation/pending-navigation-guard", async (original) => { const actual = await original<typeof import("@/lib/navigation/pending-navigation-guard")>(); return { ...actual, installPendingNavigationGuard: (options: Parameters<typeof actual.installPendingNavigationGuard>[0]) => { if (guardFault.fail) throw new Error("synthetic fault"); return actual.installPendingNavigationGuard(options); } }; });
function admit(value = fixture.snapshot, caps = fixture.caps) { observeSocialWorkAuthority(socialWorkAuthoritySignature(fixture.context)); return observeSocialWorkSnapshot(fixture.scope, false, value, caps); }
function begin(action: Parameters<typeof swInput>[1] = "create_draft") { const { input, target } = swInput(fixture.snapshot, action); return beginSocialWork(fixture.scope, false, input, fixture.snapshot.generatedAt, action === "create_draft" ? undefined : target)!; }
beforeEach(() => { vi.useFakeTimers({ toFake: ["Date"] }); vi.setSystemTime(new Date(Date.parse("2026-09-26T04:00:00.000Z") + ++serial * 10_000)); clearSocialWorkPendingOnLogout(); fixture = swFixture(); admit(); });
afterEach(() => { external?.(); external = null; guardFault.fail = false; clearSocialWorkPendingOnLogout(); document.body.innerHTML = ""; vi.restoreAllMocks(); vi.useRealTimers(); });
describe("social-work original operation journal", () => {
  it("normalizes audited snapshot while rejecting extra top/nested fields, staleAfter and history flags", () => { expect(normalizeSocialWorkSnapshot(fixture.snapshot, fixture.scope)).toEqual(fixture.snapshot); for (const value of [{ ...fixture.snapshot, secret: "x" }, { ...fixture.snapshot, staleAfter: fixture.snapshot.generatedAt }, { ...fixture.snapshot, records: fixture.snapshot.records.map((record, index) => index ? record : { ...record, secret: "x" }) }, { ...fixture.snapshot, records: fixture.snapshot.records.map((record, index) => index ? record : { ...record, versionHistoryTruncated: true }) }]) expect(() => normalizeSocialWorkSnapshot(value, fixture.scope)).toThrow(); });
  it.each(["create_draft", "revise_draft", "sign", "correct", "complete_follow_up", "cancel_follow_up"] as const)("freezes %s request/source and prohibits a second write", (action) => { const operation = begin(action); expect(operation).not.toBeNull(); expect(Object.isFrozen(operation.input)).toBe(true); expect(operation.body).toBe(JSON.stringify(socialWorkRequestBody(operation.input))); expect(hasPendingOperations()).toBe(true); expect(begin()).toBeNull(); });
  it("track captures service version and exact sequence on a signed chain without pending follow-up", () => { const snapshot = structuredClone(fixture.snapshot); const source = snapshot.records[0]!; Object.assign(source, { followUpEventId: null, followUpSequence: 0, followUpStatus: null, followUpDueOn: null, followUpPlan: null, followUpOutcome: null, followUpTransitionReason: null, followUpCommitterDisplayName: null, followUpCommittedAt: null, followUpOverdue: false, followUpHistory: [], followUpHistoryTotal: 0, followUpHistoryTruncated: false }); snapshot.metrics.pendingFollowUp -= 1; admit(snapshot); const { input } = swInput(snapshot, "track", swUuid(2), source); expect(beginSocialWork(fixture.scope, false, input, snapshot.generatedAt, source)?.input).toEqual(input); });
  it("requires exact actual source/client/predecessor/status before acquiring lease", () => { const { input, target } = swInput(fixture.snapshot, "sign"); expect(() => beginSocialWork(fixture.scope, false, input, fixture.snapshot.generatedAt, { ...target, serviceResult: "wrong" })).toThrow(); expect(() => beginSocialWork(fixture.scope, false, { ...input, clientId: fixture.snapshot.records[0]!.clientId }, fixture.snapshot.generatedAt, target)).toThrow(); expect(hasPendingOperations()).toBe(false); });
  it("external operation/view leases prevent begin without taking ownership", () => { external = tryAcquirePendingOperation(); expect(begin()).toBeNull(); clearSocialWorkPendingOnLogout(); expect(hasPendingOperations()).toBe(true); external!(); external = tryAcquireViewTransition(); admit(swFresh(fixture.snapshot)); expect(begin()).toBeNull(); });
  it("guard setup failure rolls back only the newly acquired operation and lease", () => { guardFault.fail = true; expect(() => begin()).toThrow(); expect(getSocialWorkPending().operation).toBeNull(); expect(hasPendingOperations()).toBe(false); });
  it("unknown then repeated denials retains identical key/body/token and no fresh write", () => { const operation = begin(); settleSocialWork(operation, "unknown"); for (let n = 0; n < 3; n++) { const retry = retrySocialWork(operation.token, fixture.scope, false)!; expect(retry.input.idempotencyKey).toBe(operation.input.idempotencyKey); expect(retry.body).toBe(operation.body); settleSocialWork(retry, "denied"); expect(getSocialWorkPending().operation?.phase).toBe("unknown"); } expect(begin()).toBeNull(); });
  it("first known rejection releases its own lease but malformed/errors are never confirmed", () => { const operation = begin(); settleSocialWork(operation, "denied"); expect(hasPendingOperations()).toBe(false); expect(getSocialWorkPending().confirmed).toHaveLength(0); for (const raw of [null, "<html>", {}, { requestId: swUuid(8), status: "error", data: null, errors: [{ code: "SAVE_FAILED", message: "unknown" }] }]) expect(isConfirmedSocialWorkRejection(raw, 403)).toBe(false); expect(isConfirmedSocialWorkRejection({ requestId: swUuid(8), status: "error", data: null, errors: [{ code: "SOCIAL_WORK_NOT_AUTHORIZED", message: "denied" }] }, 403)).toBe(true); });
  it("late attempt cannot settle a retry or a new operation after safe logout", () => { const old = begin(); settleSocialWork(old, "unknown"); const retry = retrySocialWork(old.token, fixture.scope, false)!; expect(settleSocialWork(old, swSuccess(old.input))).toBe(false); clearSocialWorkPendingOnLogout(); vi.setSystemTime(Date.now() + 1000); fixture.snapshot = swFresh(fixture.snapshot); admit(); const newer = begin(); expect(settleSocialWork(retry, swSuccess(retry.input))).toBe(false); expect(getSocialWorkPending().operation).toBe(newer); expect(hasPendingOperations()).toBe(true); });
  it("permission ABA invalidates response without privacy hiding legitimately readable history", () => { const operation = begin("sign"); observeSocialWorkAuthority(socialWorkAuthoritySignature({ ...fixture.context, scopes: fixture.context.scopes.filter((scope) => scope !== "social_work_records.sign") })); observeSocialWorkAuthority(socialWorkAuthoritySignature(fixture.context)); admit(); expect(settleSocialWork(operation, swSuccess(operation.input))).toBe(false); expect(retrySocialWork(operation.token, fixture.scope, false)).not.toBeNull(); });
  it("assignment SAME-generation ABA cannot revive original source across remount; fresh generation restores exact retry", () => { const operation = begin("sign"); const empty = { ...fixture.snapshot, records: [], recordTotal: 0, matchingTotal: 0, recordsTruncated: false, clientOptions: [], metrics: { currentMonth: 0, pendingFollowUp: 0, overdueFollowUp: 0, drafts: 0, signed: 0 } }; expect(admit(empty)).toBe(false); expect(retrySocialWork(operation.token, fixture.scope, false)).toBeNull(); expect(admit()).toBe(false); expect(settleSocialWork(operation, swSuccess(operation.input))).toBe(false); expect(retrySocialWork(operation.token, fixture.scope, false)).toBeNull(); vi.setSystemTime(Date.now() + 1000); expect(admit(swFresh(fixture.snapshot))).toBe(true); expect(retrySocialWork(operation.token, fixture.scope, false)?.body).toBe(operation.body); });
  it("actor/read/privacy ABA refuses retained old source, including after remount/logout", () => { const operation = begin(); const b = { ...fixture.context, userId: swUuid(9) }; observeSocialWorkAuthority(socialWorkAuthoritySignature(b)); observeSocialWorkAuthority(socialWorkAuthoritySignature(fixture.context)); expect(admit()).toBe(false); expect(retrySocialWork(operation.token, fixture.scope, false)).toBeNull(); vi.setSystemTime(Date.now() + 1000); const fresh = swFresh(fixture.snapshot); expect(admit(fresh)).toBe(true); expect(getSocialWorkSnapshotAdmission(fixture.scope, false)).toBe(fresh.generatedAt); expect(admit()).toBe(false); clearSocialWorkPendingOnLogout(); observeSocialWorkAuthority(socialWorkAuthoritySignature(fixture.context)); expect(admit(fresh)).toBe(false); expect(getSocialWorkPending().operation).toBeNull(); expect(getSocialWorkPending().confirmed).toHaveLength(0); });
  it("expiry alone prevents new writes but retains exact original manual retry", () => { const operation = begin(); settleSocialWork(operation, "unknown"); vi.setSystemTime(Date.now() + 61_000); expect(retrySocialWork(operation.token, fixture.scope, false)?.body).toBe(operation.body); });
  it("wrong-chain, wrong-version, same source ID and malformed success cannot be settled", () => { const operation = begin("sign"); const receipt = swSuccess(operation.input); for (const value of [{ ...receipt, data: { ...receipt.data, recordKey: swUuid(90) } }, { ...receipt, data: { ...receipt.data, recordVersion: 1 } }, { ...receipt, data: { ...receipt.data, versionId: operation.target!.versionId } }, { ...receipt, errors: ["bad"] }]) expect(() => settleSocialWork(operation, value as typeof receipt)).toThrow(); expect(getSocialWorkPending().operation).toBe(operation); });
  it("success retains stale-source guard: refresh, missing row and unrelated newer chain are not proof", () => { const operation = begin("sign"); settleSocialWork(operation, swSuccess(operation.input)); expect(hasPendingOperations()).toBe(false); expect(getSocialWorkPending().confirmed).toHaveLength(1); expect(begin("sign")).toBeNull(); vi.setSystemTime(Date.now() + 1000); const fresh = swFresh(fixture.snapshot); reconcileSocialWorkConfirmed(fixture.scope, fresh, Date.now()); reconcileSocialWorkConfirmed(fixture.scope, { ...fresh, records: [], matchingTotal: 0, recordsTruncated: false }, Date.now()); expect(getSocialWorkPending().confirmed).toHaveLength(1); });
  it("positive same-chain exact historical version clears marker after a fresh snapshot", () => { const operation = begin("sign"); const receipt = swSuccess(operation.input); settleSocialWork(operation, receipt); vi.setSystemTime(Date.now() + 1000); const fresh = swFresh(fixture.snapshot); const source = fresh.records.find((record) => record.recordKey === operation.target!.recordKey)!; const data = receipt.data; if (data.receiptKind !== "record") throw new Error(); const historical = { ...source.versionHistory[0]!, versionId: data.versionId, recordVersion: data.recordVersion, recordState: data.recordState, signedAt: data.committedAt, signerDisplayName: "合成社工", createdAt: data.committedAt }; Object.assign(source, { ...historical, authorUserId: source.authorUserId, versionHistory: [...source.versionHistory, historical], versionHistoryTotal: source.versionHistoryTotal + 1 }); fresh.metrics.drafts -= 1; fresh.metrics.signed += 1; reconcileSocialWorkConfirmed(fixture.scope, fresh, Date.now()); expect(getSocialWorkPending().confirmed).toHaveLength(0); });
  it("demo and foreign scope cannot create or see accepted generation", () => { const { input } = swInput(fixture.snapshot); expect(beginSocialWork(fixture.scope, true, input, fixture.snapshot.generatedAt)).toBeNull(); expect(beginSocialWork({ ...fixture.scope, userId: swUuid(99) }, false, input, fixture.snapshot.generatedAt)).toBeNull(); expect(getSocialWorkSnapshotAdmission({ ...fixture.scope, userId: swUuid(99) }, false)).toBeNull(); });
  it("same-tab cross-origin navigation and GET submission remain blocked while unknown", () => { const operation = begin(); settleSocialWork(operation, "unknown"); const a = document.createElement("a"); a.href = "https://finance.suiyuecare.com"; document.body.append(a); const event = new MouseEvent("click", { bubbles: true, cancelable: true, button: 0 }); a.dispatchEvent(event); expect(event.defaultPrevented).toBe(true); const form = document.createElement("form"); form.method = "get"; document.body.append(form); const submit = new Event("submit", { bubbles: true, cancelable: true }); form.dispatchEvent(submit); expect(submit.defaultPrevented).toBe(true); expect(getSocialWorkPending().navigationBlocked).toBe(true); });
  it("32 bounded markers cannot be bypassed by refresh or a new key; logout clears all clinical state", () => {
    const snapshot = structuredClone(fixture.snapshot); const base = snapshot.clientOptions[0]!; snapshot.clientOptions = [...snapshot.clientOptions, ...Array.from({ length: 33 }, (_, index) => ({ ...base, clientId: swUuid(200 + index), displayName: `合成${index}` }))]; admit(snapshot);
    for (let index = 0; index < 32; index++) { const { input } = swInput(snapshot); const value = { ...input, clientId: swUuid(200 + index), idempotencyKey: swUuid(300 + index) }; const operation = beginSocialWork(fixture.scope, false, value, snapshot.generatedAt)!; expect(operation).not.toBeNull(); const receipt = swSuccess(value); settleSocialWork(operation, { ...receipt, data: { ...receipt.data, operationId: swUuid(400 + index), recordKey: swUuid(500 + index), versionId: swUuid(600 + index) } } as typeof receipt); }
    const { input } = swInput(snapshot); expect(beginSocialWork(fixture.scope, false, { ...input, clientId: swUuid(232), idempotencyKey: swUuid(332) }, snapshot.generatedAt)).toBeNull(); reconcileSocialWorkConfirmed(fixture.scope, snapshot, Date.now()); expect(getSocialWorkPending().confirmed).toHaveLength(32); clearSocialWorkPendingOnLogout(); expect(getSocialWorkPending().confirmed).toHaveLength(0); expect(getSocialWorkPending().operation).toBeNull(); expect(hasPendingOperations()).toBe(false); expect(getSocialWorkPending().snapshotFloor).toBe(snapshot.generatedAt);
  });
});
