import type {
  ModuleId,
  OfflineMode,
  PageCatalogEntry,
  PageOrigin,
} from "./types";

type StaffPageInput = Omit<
  PageCatalogEntry,
  | "number"
  | "slug"
  | "moduleId"
  | "surface"
  | "origin"
  | "offline"
  | "requiredPermissions"
> & {
  origin?: Extract<PageOrigin, "parity" | "governance">;
  offlineMode?: OfflineMode;
  offlineNote?: string;
  requiredPermissions?: readonly string[];
};

function staffPage(
  number: number,
  moduleId: Exclude<ModuleId, "family-portal">,
  segment: string,
  input: StaffPageInput,
): PageCatalogEntry {
  const offlineMode = input.offlineMode ?? "online-only";
  const offlineNote =
    input.offlineNote ??
    (offlineMode === "online-only"
      ? "此頁涉及正式或敏感資料，只能在線上使用。"
      : "僅保存當日最小必要資料，最長 24 小時；登出即清除。");

  return {
    number,
    slug: `staff/${moduleId}/${segment}`,
    moduleId,
    surface: "staff",
    origin: input.origin ?? "parity",
    title: input.title,
    description: input.description,
    primaryActions: input.primaryActions,
    filters: input.filters,
    metrics: input.metrics,
    columns: input.columns,
    acceptance: input.acceptance,
    requiredPermissions: input.requiredPermissions ?? [],
    riskLevel: input.riskLevel,
    offline: { mode: offlineMode, note: offlineNote },
  };
}

export const staffPages = [
  staffPage(1, "workspace", "dashboard", {
    title: "首頁／工作儀表板",
    description: "整合當日出勤、量測、交通、待辦與異常工作。",
    primaryActions: ["查看明細", "切換分支", "前往待辦"],
    filters: ["日期", "分支"],
    metrics: ["出勤人數", "量測完成率", "交通待辦", "異常件數"],
    columns: ["工作類型", "待辦數", "完成數", "異常數", "更新時間"],
    acceptance: ["卡片數字可下鑽至相同口徑明細，且資料更新延遲不超過 60 秒。"],
    riskLevel: "sensitive",
  }),
  staffPage(2, "workspace", "case-center", {
    title: "個案中心",
    description: "以穩定個案識別碼搜尋並進入個案工作。",
    primaryActions: ["查看個案", "新增紀錄", "清除篩選"],
    filters: ["關鍵字", "分支", "服務狀態", "負責人"],
    metrics: ["符合個案數", "服務中", "即將複評", "有警示"],
    columns: ["個案", "服務狀態", "負責人", "最近服務", "警示"],
    acceptance: ["每位個案僅顯示一筆；返回時保留篩選、分頁與捲動位置。"],
    requiredPermissions: ["clients.read"],
    riskLevel: "sensitive",
  }),

  staffPage(3, "daily-care", "vital-signs", {
    title: "生命徵象紀錄",
    description: "記錄並追蹤個案當日生命徵象。",
    primaryActions: ["新增量測", "儲存草稿", "查看趨勢"],
    filters: ["日期", "分支", "個案", "量測狀態"],
    metrics: ["應量人數", "已量人數", "未量人數", "異常筆數"],
    columns: ["個案", "量測時間", "血壓", "脈搏", "體溫", "血氧", "狀態"],
    acceptance: ["已量與未量合計等於當日適用個案數，最新有效量測含明確時間。"],
    requiredPermissions: ["clients.read", "health.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(4, "daily-care", "blood-glucose", {
    title: "血糖紀錄",
    description: "記錄餐前、餐後及其他情境的血糖值。",
    primaryActions: ["新增血糖", "儲存草稿", "查看趨勢"],
    filters: ["服務狀態", "日期", "個案", "量測情境"],
    metrics: ["今日應量", "今日已量", "異常筆數", "待確認"],
    columns: ["個案", "量測時間", "情境", "數值", "單位", "來源", "狀態"],
    acceptance: ["量測依發生時間排序，網路重送使用冪等鍵且不得新增重複紀錄。"],
    requiredPermissions: ["clients.read", "health.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(5, "daily-care", "insulin", {
    title: "胰島素施打紀錄",
    description: "依有效醫囑記錄胰島素施打與雙人覆核。",
    primaryActions: ["記錄施打", "獨立覆核", "授權逾時補登", "查看計畫證據"],
    filters: ["日期", "班別", "個案", "覆核狀態"],
    metrics: ["應施打", "已施打", "待覆核", "例外"],
    columns: ["個案", "醫囑", "劑量", "部位", "施打時間", "執行人", "覆核人"],
    acceptance: [
      "Page 8 已核准、於排程時點有效且未停止的唯一版本，連同明確胰島素指定，才可成為施打計畫證據；不得建立平行計畫主權。",
      "資格 taxonomy、Page 72 最新有效證照、版本化劑量規則或補登規則任一未發布時均明示 not_configured，施打、覆核與補登授權全部 fail closed。",
      "所有施打均保存精確 decimal text、單位、部位、排程、伺服器執行時間、計畫版本與資格證據；同一計畫時點唯一且 exact replay 不重複。",
      "執行與獨立覆核為兩位不同且當下具有效資格的人員，兩者皆須同一工作階段最近 15 分鐘 AAL2；逾時補登另須不同督導理由與授權。",
      "操作權限在解析敏感 body 前驗證；正式流程不離線、不採 client time，合成 Demo 唯讀且不得宣稱完成或外部送達。",
    ],
    requiredPermissions: ["clients.read", "medications.read", "insulin_administrations.read"],
    riskLevel: "high",
    offlineMode: "online-only",
  }),
  staffPage(6, "daily-care", "care-diary", {
    title: "照顧日誌",
    description: "記錄班別照顧內容、觀察、異常與處置。",
    primaryActions: ["新增日誌", "儲存草稿", "標記異常"],
    filters: ["日期", "班別", "個案", "異常狀態"],
    metrics: ["今日完成", "今日未完成", "異常件數", "有附件"],
    columns: ["個案", "班別", "照顧項目", "紀錄時間", "紀錄人", "異常"],
    acceptance: ["新增或更正後，個案最新日期、今日狀態與異常標記立即一致更新。"],
    requiredPermissions: ["clients.read", "care_records.read"],
    riskLevel: "sensitive",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(7, "daily-care", "medication-records", {
    title: "用藥紀錄 2.0",
    description: "依排程管理服用、拒絕、暫停與漏服。",
    primaryActions: ["記錄用藥", "登記例外", "完成簽署"],
    filters: ["日期", "班別", "給藥時點", "狀態", "個案"],
    metrics: ["應給藥", "已完成", "待處理", "例外"],
    columns: ["個案", "藥物", "時點", "狀態", "原因", "執行人", "簽署時間"],
    acceptance: ["每個排程藥物時點僅有一個狀態，拒絕、暫停與漏服必須填寫原因。"],
    requiredPermissions: ["clients.read", "medications.read"],
    riskLevel: "high",
  }),
  staffPage(8, "daily-care", "medication-plans", {
    title: "用藥計畫 2.0",
    description: "建立具生效日期及版本的個案用藥計畫。",
    primaryActions: ["新增版本", "停用藥物", "比較版本"],
    filters: ["個案", "生效狀態", "藥物", "版本"],
    metrics: ["有效計畫", "即將到期", "近期異動", "待簽署"],
    columns: ["個案", "版本", "藥物", "用法", "生效日", "停藥日", "狀態"],
    acceptance: ["任一時間點只有一個有效版本，新增版本不得改寫既有用藥執行歷史。"],
    requiredPermissions: ["clients.read", "medications.read"],
    riskLevel: "high",
  }),
  staffPage(9, "daily-care", "client-tocc", {
    title: "個案 TOCC",
    description: "管理個案旅遊、職業、接觸與群聚紀錄效期。",
    primaryActions: ["新增紀錄", "批次登錄", "查看到期"],
    filters: ["個案", "日期", "有效狀態", "結果"],
    metrics: ["有效紀錄", "即將到期", "已到期", "需處置"],
    columns: ["個案", "填報日", "有效至", "結果", "處置", "紀錄人"],
    acceptance: ["單筆與批次共用相同驗證及一個月效期規則，批次逐筆回報結果。"],
    requiredPermissions: ["clients.read", "health.read"],
    riskLevel: "high",
  }),
  staffPage(10, "daily-care", "individual-service-plan", {
    title: "個別化服務計畫",
    description: "管理每月個別化目標、活動、頻率與進度。",
    primaryActions: ["建立本月計畫", "更新進度", "複製前期"],
    filters: ["月份", "個案", "負責人", "狀態"],
    metrics: ["本月計畫", "待完成", "進行中", "已完成"],
    columns: ["個案", "月份", "目標", "頻率", "負責人", "進度", "狀態"],
    acceptance: ["依 Asia/Taipei 判定月份，新月份建立獨立版本且不覆寫舊月份。"],
    requiredPermissions: ["clients.read", "care_plans.read"],
    riskLevel: "sensitive",
  }),

  staffPage(11, "assessments", "spmsq", {
    title: "SPMSQ 評估",
    description: "依衛福部公開表單逐題記錄 10 題作答；分數與判讀仍屬候選規則。",
    primaryActions: ["開始候選草稿", "建立候選草稿新版", "查看不可變版本"],
    filters: ["個案", "候選試算狀態", "教育脈絡"],
    metrics: ["候選試算可重現", "試算不完整", "尚未建立", "候選草稿"],
    columns: [
      "個案", "最近候選草稿", "答案完整度", "教育／文化脈絡",
      "候選試算（非正式）", "操作",
    ],
    acceptance: [
      "畫面逐題呈現台灣衛福部 SPMSQ 10 題與施測提示，第 4 題無電話時可改問居住地，並標示原始來源。",
      "候選錯誤數須由 spmsq-pfeiffer-10-education-adjusted-v1 不可變候選規則快照重現；此教育調整規則與台灣衛福部表單呈現方式尚待專業覆核，不得啟用為正式計分。文化脈絡只保存，不改變數值。",
      "未回答與不適用須分開保存，任一題未回答、不適用或教育脈絡不完整時試算為不完整，不得視為 0 分。",
      "候選規則未正式啟用時，正式簽署、官方分數、診斷與照顧決策一律 fail closed。",
      "正式資料依機構、分支與指派個案隔離，且須具 clients.read、assessments.read/manage 與最近 15 分鐘 AAL2；未授權請求在解析內容前拒絕。",
      "草稿採不可變線性版本鏈、預期版本與使用者範圍冪等鍵；查閱與寫入稽核不得保存答案、個資或搜尋內容。",
      "附件、匯出與離線同步未配置，介面明示 not_configured 並維持僅線上操作。",
    ],
    requiredPermissions: ["clients.read", "assessments.read"],
    riskLevel: "high",
  }),
  staffPage(12, "assessments", "gds", {
    title: "GDS 老人憂鬱量表",
    description: "保存十五題明確答案狀態與不可變候選規則快照；未啟用前只提供受治理草稿與非正式試算。",
    primaryActions: ["開始候選草稿", "建立不可變新版", "查看版本歷程"],
    filters: ["個案", "候選試算狀態", "答案狀態"],
    metrics: ["候選試算可重現", "試算不完整", "尚未建立", "候選草稿"],
    columns: ["個案", "最近候選草稿", "答案完整度", "候選試算（非正式）", "操作"],
    acceptance: [
      "固定答案的候選點數與區間須由 gds-15-strict-complete-v1 不可變規則快照重現；任何缺值或不適用均不產生數值。",
      "未回答與不適用分開保存且不得當作 0；十五個題位採嚴格鍵集合，不接受未知、缺漏或額外欄位。",
      "候選規則未經雙人核准 activated 前，正式簽署、正式分數、正式風險分類、診斷與照顧決策一律 fail closed。",
      "正式資料依機構、分支與指派個案隔離，且需 clients.read、gds_assessments.read/manage 與最近 15 分鐘 AAL2；未授權請求在解析內容前拒絕。",
      "草稿採不可變線性版本鏈、預期版本與使用者範圍冪等鍵；查閱與寫入稽核不得保存答案、個資或篩選值。",
      "附件、匯出、離線同步與通知未配置，介面明示 not_configured 並維持 fail closed。",
    ],
    requiredPermissions: ["clients.read", "gds_assessments.read"],
    riskLevel: "high",
  }),
  staffPage(13, "assessments", "fall-risk", {
    title: "跌倒風險評估",
    description: "保存六項人工觀察因子的三態答案與不可變候選規則快照；規則未啟用前不得產生正式結果或處置。",
    primaryActions: ["開始候選草稿", "建立不可變新版", "查看版本歷程"],
    filters: ["個案", "候選試算狀態", "答案狀態"],
    metrics: ["候選試算可重現", "試算不完整", "尚未建立", "候選草稿"],
    columns: ["個案", "最近候選草稿", "答案完整度", "候選試算（非正式）", "操作"],
    acceptance: [
      "六項人工觀察因子、present／absent 候選計數與區間須由 fall-risk-manual-factors-candidate-v1 不可變快照重現；這不是官方量表、臨床分數、診斷或正式風險分級。",
      "已回答、缺值與不適用分開保存；任一缺值或不適用均不產生候選點數，且不得當作 0。",
      "規則未經雙人核准 activated 前，正式簽署、正式分數、正式風險分級、建議處置與照顧決策一律 fail closed。",
      "候選高檢視不得自動建立或生效待辦，也不得通知；待辦建議規則未發布時明示 not_configured。",
      "正式資料依機構、分支與指派個案隔離，且需 clients.read、fall_risk_assessments.read/manage 與最近 15 分鐘 AAL2；受治理 action header、授權及 AAL2 在解析內容前驗證。",
      "草稿採不可變線性版本鏈、預期版本、內容與規則雜湊及使用者範圍冪等鍵；查閱與寫入稽核不得保存答案、個資或篩選值。",
      "附件、匯出、離線同步與通知未配置，介面明示 not_configured 並維持 fail closed。",
    ],
    requiredPermissions: ["clients.read", "fall_risk_assessments.read"],
    riskLevel: "high",
  }),
  staffPage(14, "assessments", "nsi", {
    title: "NSI 營養篩檢",
    description: "正式題本未提供前，只保存六項中性人工營養觀察與不可變候選欄位快照。",
    primaryActions: ["開始人工觀察草稿", "建立不可變新版", "查看版本歷程"],
    filters: ["個案", "人工觀察重播狀態", "答案狀態"],
    metrics: ["人工觀察可重播", "重播不完整", "尚未建立", "人工觀察草稿"],
    columns: ["個案與服務狀態", "最近人工觀察草稿", "答案完整度", "人工觀察重播（非正式）", "操作"],
    acceptance: [
      "正式 NSI 題本、題目文字、權重、授權來源與風險分類未提供時，只能保存 manual_unstandardized／candidate_unactivated 人工營養觀察草稿，不得冒充正式 NSI。",
      "六項中性人工觀察的已出現、未出現、缺值與不適用須明確分開；任一缺值或不適用均不產生項目數，且項目數不得標示或解讀為分數。",
      "候選欄位與完整性規則保存不可變版本快照及雜湊；固定合成向量可重播相同的非臨床已出現項目數，不產生權重、風險區間或診斷。",
      "正式題本與規則未經雙人核准發布前，正式簽署、正式分數、風險分類、診斷、照顧決策、營養追蹤及轉介一律 fail closed，且不得自動建立或通知追蹤。",
      "正式資料依機構、分支與指派個案隔離，且需 clients.read、nsi_nutrition_screenings.read/manage 與最近 15 分鐘 AAL2；受治理 action header、授權及 AAL2 在解析內容前驗證。",
      "草稿採不可變線性版本鏈、預期版本、內容與規則雜湊及使用者範圍冪等鍵；查閱與寫入稽核不得保存答案、個資或篩選值。",
      "附件、匯出、離線同步與通知未配置，介面明示 not_configured 並維持 fail closed。",
    ],
    requiredPermissions: ["clients.read", "nsi_nutrition_screenings.read"],
    riskLevel: "high",
  }),
  staffPage(15, "assessments", "barthel-adl", {
    title: "Barthel ADL",
    description: "評估日常生活活動能力與依賴程度。",
    primaryActions: ["開始評估", "比較歷次", "簽署結果"],
    filters: ["個案", "評估日期", "依賴程度", "複評狀態"],
    metrics: ["獨立", "輕度依賴", "中重度依賴", "待複評"],
    columns: ["個案", "評估日期", "版本", "總分", "依賴程度", "複評日", "簽署"],
    acceptance: ["各項及總分可用版本化公式重算，超出合法選項的數值不可儲存。"],
    riskLevel: "high",
  }),
  staffPage(16, "assessments", "iadl", {
    title: "IADL",
    description: "評估工具性日常生活活動能力。",
    primaryActions: ["開始評估", "比較歷次", "簽署結果"],
    filters: ["個案", "評估日期", "能力分級", "複評狀態"],
    metrics: ["已完成", "待複評", "逾期", "功能下降"],
    columns: ["個案", "評估日期", "版本", "分數", "分級", "複評日", "簽署"],
    acceptance: ["缺值與不適用分開保存，性別或不適用規則依當時版本計算。"],
    riskLevel: "high",
  }),
  staffPage(17, "assessments", "swallowing", {
    title: "吞嚥評估",
    description: "評估吞嚥風險並串聯飲食質地與轉介。",
    primaryActions: ["開始評估", "調整飲食建議", "建立轉介"],
    filters: ["個案", "評估日期", "風險", "轉介狀態"],
    metrics: ["正常", "需留意", "高風險", "待轉介"],
    columns: ["個案", "評估日期", "風險", "飲食質地", "處置", "轉介", "簽署"],
    acceptance: ["高風險結果未被具權限人員確認及記錄處置前不得結案。"],
    riskLevel: "high",
  }),
  staffPage(18, "assessments", "bsrs", {
    title: "BSRS 情緒量表",
    description: "評估情緒困擾程度及特殊題風險。",
    primaryActions: ["開始評估", "確認警示", "簽署結果"],
    filters: ["個案", "評估日期", "風險分級", "警示狀態"],
    metrics: ["一般", "輕度", "中重度", "特殊題警示"],
    columns: ["個案", "評估日期", "總分", "分級", "特殊題", "處置", "簽署"],
    acceptance: ["黃金答案產生正確總分與分級，特殊題警示須由授權人員明確確認。"],
    riskLevel: "high",
  }),
  staffPage(19, "assessments", "physical", {
    title: "身體評估",
    description: "人工非標準化文字觀察：明確選擇部位、保存狀況與人工處置；正式表單及照片未配置。",
    primaryActions: ["新增評估草稿", "修訂草稿", "核對並簽署", "建立更正版"],
    filters: ["個案", "紀錄狀態"],
    metrics: ["可見紀錄", "草稿", "已簽署", "已更正"],
    columns: ["個案", "觀察時間", "選定部位", "狀況", "人工處置", "版本", "簽署"],
    acceptance: ["所有適用必填部位完成後才能簽署，異常描述、照片與處置均完整保留。"],
    riskLevel: "high",
    requiredPermissions: ["clients.read", "body_assessments.read"],
  }),
  staffPage(20, "assessments", "behavior-emotion", {
    title: "行為與情緒紀錄",
    description: "以不可變事件版本分欄保存前因、行為、人工處置與人工結果。",
    primaryActions: ["新增事件草稿", "修訂草稿", "簽署", "有理由更正", "必要作廢"],
    filters: ["個案", "事件日期", "事件類型", "紀錄狀態"],
    metrics: ["事件數", "含缺值", "草稿", "已簽／更正", "已作廢"],
    columns: ["個案", "發生時間", "前因", "行為", "處置", "結果", "紀錄人"],
    acceptance: [
      "每次事件以穩定事件鍵獨立保存，清單依 occurred_at 而非 created_at 排序；後續輸入不得改寫原版本。",
      "前因、行為、人工處置與人工結果逐欄明確保存 recorded、missing 或 not_applicable，缺值不得視為空字或零。",
      "事件類型、四欄內容及結果皆由人員明確輸入；系統不得從敘事自動推論欄位、診斷或照顧決策。",
      "草稿修訂使用不可變線性版本、expected version、內容雜湊及使用者範圍 exact replay；已簽內容只能建立有理由更正版，必要作廢亦須理由。",
      "簽署、更正與作廢須專頁 sign 權限及同一工作階段最近 15 分鐘 AAL2；員工 AAL2 與專頁權限在解析敏感 body 前驗證。",
      "正式資料依機構、分支與指派個案隔離；完整集合統計不受 200 筆顯示上限影響，查閱稽核不得保存搜尋值或敘事。",
      "附件、外部通知、匯出及 24 小時離線草稿未配置時須明示 not_configured 並 fail closed。",
    ],
    requiredPermissions: ["clients.read", "behavior_events.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "24 小時離線草稿尚未配置；正式事件、簽署、更正與作廢只能在線上進行。",
  }),
  staffPage(21, "assessments", "abcd", {
    title: "ABCD 評估",
    description: "以人工、非標準化候選格式，分開保存 A、B、C、D 類型及年度版本。",
    primaryActions: ["新增候選草稿", "修訂草稿", "簽署人工紀錄", "有理由更正"],
    filters: ["個案", "年度", "類型", "複評狀態", "紀錄狀態", "個案名稱或評估代碼"],
    metrics: ["符合評估", "A 類", "B 類", "C 類", "D 類", "複評日期缺值", "草稿", "已簽／更正"],
    columns: ["個案與評估日", "年度與類型", "人工摘要", "結果三態與理由", "複評日期三態與依據", "版本與簽署"],
    acceptance: [
      "個案、評估年度及 A／B／C／D 類型共同定義唯一且不可變的線性版本鏈；不同類型或年度不得互相覆寫或在既有鏈上切換。",
      "正式題本、公式、代碼與授權來源未核准前，僅保存 manual_unstandardized 人工候選摘要、結果三態與理由、人工複評日期三態與依據；不得建立分數、診斷、自動複評或照顧決策。",
      "正式發布規則未配置時，畫面與快照須明示未配置並 fail closed，不得將人工候選紀錄標示成官方或標準化 ABCD 結果。",
      "草稿修訂、簽署及更正只追加不可變線性版本，使用 expected terminal version、內容雜湊及 actor-scoped exact replay；簽署與更正須同一工作階段最近 15 分鐘 AAL2。",
      "所有寫入在解析敏感 body 前驗證員工 AAL2、clients.read、abcd_assessments.read／manage；資料庫再次限制機構、分支及指派個案。",
      "個案、年度、類型、複評三態、紀錄狀態與查詢均採嚴格單值白名單；完整集合統計先於 200 筆顯示截斷，查閱稽核不得保存摘要、結果、理由或查詢值。",
      "附件、匯出、通知與離線未配置時須明示未配置並 fail closed。",
    ],
    requiredPermissions: ["clients.read", "abcd_assessments.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線候選草稿尚未配置；建立、修訂、簽署與更正只能在線上進行。",
  }),
  staffPage(22, "assessments", "inspection-reports", {
    title: "檢查報告",
    description: "以不可變版本保存已指派個案的檢查類型、日期、結果三態、來源三態與可信附件證據。",
    primaryActions: ["新增報告", "建立更正版", "追加作廢終端"],
    filters: ["個案", "檢查日期", "檢查類型", "結果狀態", "來源狀態", "附件狀態", "重複層級"],
    metrics: ["報告數", "缺結果", "缺附件", "重複警示"],
    columns: ["個案", "檢查日期", "檢查類型", "結果三態", "來源三態", "可信附件證據", "版本與警示"],
    acceptance: [
      "僅允許 AAL2 員工依分支、個案指派、health.read 與 client_reports.read 查看，跨範圍為零。",
      "建立、更正與作廢形成不可變單一終端鏈；更正與作廢須同一工作階段最近 15 分鐘 AAL2。",
      "結果與來源明確區分已提供、缺值與不適用，缺值理由不得為空；不提供醫療判讀、診斷或 OCR。",
      "內容完全相同、同個案類型日期來源及相同附件 SHA-256 分級警示，但不自動合併。",
      "附件上傳、掃毒、私有下載與匯出未配置時一律 fail closed，不接受任意附件 ID。",
    ],
    requiredPermissions: ["clients.read", "health.read", "client_reports.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "結果、來源、附件證據、更正與作廢只能在線上使用；不保存離線快取。",
  }),
  staffPage(23, "assessments", "vaccinations", {
    title: "疫苗紀錄",
    description: "以不可變版本保存個案疫苗、劑次、日期、批號、院所、證明三態與來源。",
    primaryActions: ["新增紀錄", "批次登錄", "建立更正版", "作廢終端版本"],
    filters: ["個案", "疫苗", "劑次", "日期", "狀態", "關鍵字"],
    metrics: ["終端紀錄", "本月接種日期", "缺證明", "重複警示"],
    columns: ["個案", "疫苗／劑次", "日期／批號", "院所／證明", "來源", "重複比對", "版本／狀態"],
    acceptance: [
      "每筆紀錄保存疫苗名稱、劑次、接種日期、批號、院所、證明三態及來源；缺證明與不適用分開，且不得推論醫療適用性、保護力、禁忌或下一劑。",
      "同一個案加上正規化疫苗名稱與劑次相同時列出其他獨立紀錄並警示；日期、批號或院所不同亦不得自動合併。",
      "建立、更正及作廢使用不可變單一終端版本鏈、expected version、內容雜湊及 actor-scoped exact replay；更正與作廢須理由及同一工作階段最近 15 分鐘 AAL2。",
      "單筆與最多 20 筆批次共用相同伺服器及資料庫驗證；批次以外層操作鍵精確重播，逐筆回報 created、replayed 或 rejected，變更內容不得產生尾端副作用。",
      "正式讀寫同時受機構、分支、clients.read、client_vaccinations 專頁權限與 assigned-client 限制；個案非在案或接種日期晚於 Asia/Taipei 今日時拒絕。",
      "附件上傳、掃毒、短效下載、提醒排程與離線快取未配置時明示 not_configured 並 fail closed；瀏覽器不得提交任意附件參照。",
    ],
    requiredPermissions: ["clients.read", "client_vaccinations.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "疫苗紀錄、更正、作廢及批次登錄只能在線上使用；附件、提醒與離線快取尚未配置。",
  }),

  staffPage(24, "quality", "falls", {
    title: "跌倒事件",
    description: "追蹤跌倒事件、傷害、處置、改善與結案。",
    primaryActions: ["新增事件", "更新處置", "完成結案"],
    filters: ["事件日期", "傷害程度", "處理狀態", "個案"],
    metrics: ["事件數", "有傷害", "待處置", "待結案"],
    columns: ["個案", "事件時間", "地點", "傷害程度", "處置", "負責人", "狀態"],
    acceptance: ["事件、即時處置、追蹤與結案以同一事件 ID 完整串聯且不重複計數。"],
    requiredPermissions: ["clients.read", "quality_events.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(25, "quality", "infections", {
    title: "感染事件",
    description: "管理感染事件、處置、群聚關聯與結案。",
    primaryActions: ["新增事件", "關聯群聚", "更新處置"],
    filters: ["事件日期", "感染類型", "狀態", "群聚"],
    metrics: ["事件數", "疑似群聚", "待處置", "已結案"],
    columns: ["個案", "事件日期", "感染類型", "群聚", "處置", "負責人", "狀態"],
    acceptance: ["事件可追溯類型、日期、處置與群聚關聯，同一事件在指標中只計一次。"],
    requiredPermissions: ["clients.read", "quality_events.read"],
    riskLevel: "high",
  }),
  staffPage(26, "quality", "weight-management", {
    title: "體重管理",
    description: "追蹤月間體重變化與版本化風險門檻。",
    primaryActions: ["新增體重", "更正／作廢量測", "確認警示"],
    filters: ["月份", "個案", "變化方向", "警示狀態"],
    metrics: ["符合個案", "已量人數", "缺測人數", "門檻警示"],
    columns: ["個案", "本月體重", "上月體重", "差異公斤", "差異百分比", "警示", "量測日"],
    acceptance: ["公斤及百分比月差計算正確，缺測保持缺值且不得視為零。"],
    requiredPermissions: ["clients.read", "quality_events.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(27, "quality", "incidents", {
    title: "異常事件",
    description: "通報並追蹤一般異常事件至改善結案。",
    primaryActions: ["新增通報", "更新改善", "完成結案"],
    filters: ["起日", "迄日", "事件類型", "影響對象", "狀態"],
    metrics: ["事件數", "重大事件", "待改善", "逾期"],
    columns: ["事件時間", "類型", "影響對象", "通報人", "改善", "負責人", "狀態"],
    acceptance: ["日期查詢包含起訖日，事件從通報、改善到結案皆可追溯。"],
    requiredPermissions: ["clients.read", "quality_events.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),

  staffPage(28, "social-work", "psychosocial-assessment", {
    title: "心理社會評估",
    description: "以人工、非標準化版本紀錄家庭互動、社會支持、參與、溝通情境與資源取得。",
    primaryActions: ["快速新增草稿", "建立草稿新版", "簽署評估", "建立更正版"],
    filters: ["個案", "負責人", "服務狀態", "複評期限"],
    metrics: ["已完成", "尚未評估", "今日以前到期", "尚未到期"],
    columns: ["個案／服務狀態", "最近評估", "人工摘要", "結構化面向", "人工期限", "操作"],
    acceptance: [
      "組合篩選依精確個案、原負責人、目前服務狀態與人工複評期限執行，且只涵蓋機構、分支及指派個案。",
      "manual-psychosocial-v1 明示為人工非標準化紀錄；每個面向區分已記錄、未知及不適用，不建立分數、公式或診斷。",
      "草稿只能追加新版；簽署需最近 15 分鐘 AAL2，已簽內容只能建立帶理由且連回原版本的更正版。",
      "到期規則、附件、匯出及離線正式同步未發布時皆明示 not_configured，不得宣稱已完成。",
    ],
    requiredPermissions: ["clients.read", "social_work_records.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線正式同步尚未設定；不得把本機內容宣稱為已送達或已完成。",
  }),
  staffPage(29, "social-work", "service-records", {
    title: "社工服務紀錄",
    description: "記錄社工服務內容、結果與後續追蹤。",
    primaryActions: ["新增服務", "建立追蹤", "簽署紀錄"],
    filters: ["個案", "日期", "服務類型", "作者"],
    metrics: ["服務筆數", "本月服務", "待追蹤", "逾期"],
    columns: ["個案", "服務日期", "服務類型", "內容摘要", "結果", "作者", "狀態"],
    acceptance: [
      "每筆服務保存實際發生時間、類型、內容、結果及作者，時間軸依發生時間而非輸入時間排序。",
      "草稿、追蹤、簽署與有理由的更正版形成不可覆寫版本鏈；簽署須最近 15 分鐘 AAL2。",
      "所有讀寫同時受機構、分支及指派個案範圍限制；離線正式同步未設定時明確拒絕宣稱已送達。",
    ],
    requiredPermissions: ["clients.read", "social_work_records.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線正式同步尚未設定；不得把本機內容宣稱為已送達或已完成。",
  }),
  staffPage(30, "social-work", "activities", {
    title: "活動管理",
    description: "規劃活動、參與者、場地、負責人與執行狀態。",
    primaryActions: ["建立活動", "管理參與者", "取消活動"],
    filters: ["日期", "分支", "活動類型", "狀態", "關鍵字"],
    metrics: ["活動數", "即將舉行", "已完成", "已取消"],
    columns: ["活動", "時間", "地點", "負責人", "參與人數", "狀態", "取消原因"],
    acceptance: ["活動時間、地點、負責人、參與者與狀態形成不可覆寫版本；取消原因及近期 AAL2 必填。外部通知規則未設定時明確不發送。"],
    requiredPermissions: ["clients.read", "activity.read"],
    riskLevel: "sensitive",
  }),
  staffPage(31, "social-work", "resources", {
    title: "社會資源管理",
    description: "維護可供個案使用的補助、福利與社區資源。",
    primaryActions: ["新增資源", "更新確認日", "停用資源"],
    filters: ["年度", "資源類型", "狀態", "適用對象", "關鍵字"],
    metrics: ["有效資源", "即將到期", "待確認", "已停用"],
    columns: ["資源", "類型", "適用對象", "資格", "有效期限", "最後確認日", "狀態"],
    acceptance: ["每項資源均有資格、聯絡方式、適用對象、有效期限及最後確認日。"],
    requiredPermissions: ["social_resources.read"],
    riskLevel: "standard",
  }),
  staffPage(32, "social-work", "adaptation-assessment", {
    title: "適應評估",
    description: "以人工摘要與人工狀態追蹤個案進入日照後的環境與服務適應。",
    primaryActions: ["從個案列快速新增", "簽署評估", "建立追蹤"],
    filters: ["個案", "目前服務狀態", "評估狀態", "複評期限", "人工適應狀態", "追蹤狀態"],
    metrics: ["已完成評估", "尚未評估", "複評到期", "需追蹤"],
    columns: ["個案與服務狀態", "最近評估", "人工摘要", "人工複評期限", "追蹤狀態", "操作"],
    acceptance: [
      "每位指派個案只顯示一列，列內呈現最近評估、目前服務狀態、人工輸入複評期限及需追蹤狀態。",
      "列表快速新增鎖定該列精確個案識別碼；完成憑證再次核對個案，儲存後立即重新載入最新狀態。",
      "第一版僅保存人工評估摘要與人工適應狀態，明示 manual-adaptation-v1 為非標準化技術參照；不得宣稱官方量表、計分公式或自動診斷。",
      "草稿、簽署、有理由更正及追蹤形成不可覆寫版本鏈；簽署與更正須最近 15 分鐘 AAL2。",
      "所有讀寫同時受機構、分支及指派個案範圍限制；離線正式同步未設定時明確拒絕宣稱已送達。",
    ],
    requiredPermissions: ["clients.read", "social_work_records.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線正式同步尚未設定；不得把本機內容宣稱為已送達、已完成或已簽署。",
  }),

  staffPage(33, "professional-care", "occupational-assessment", {
    title: "職能治療評估",
    description: "以人工、非標準化方式保存職能治療測量、觀察、目標、建議及追蹤。",
    primaryActions: ["開始新評估草稿", "建立草稿新版", "簽署評估", "建立更正版"],
    filters: ["個案", "職能治療師", "目前服務狀態", "人工複評期限"],
    metrics: ["已完成評估", "尚未評估", "今日以前到期", "尚未到期"],
    columns: ["個案與服務狀態", "最近評估與治療師", "人工測量", "觀察、目標、建議與追蹤", "人工期限", "操作"],
    acceptance: [
      "每位指派個案只顯示一列，呈現最近評估、目前負責職能治療師、人工輸入複評期限與期限依據。",
      "每項人工測量保存名稱、精確數值文字或觀察文字、單位，以及明確缺值或不適用理由；不得加總成臨床分數。",
      "第一版固定 manual_unstandardized 與 manual-occupational-therapy-v1 技術參照；官方／機構規則未發布時，公式、計分、診斷與自動期限均明示未配置。",
      "只有目前 professional 且具職能治療專用權限者可新增、修訂、簽署或更正；所有讀寫同時受機構、分支及指派個案範圍限制。",
      "草稿新版、最近 15 分鐘 AAL2 簽署及有理由更正形成不可覆寫線性版本鏈，舊版可依當時人工內容完整重現。",
      "附件、匯出、提醒與離線正式同步未設定時須失敗即關閉，不得宣稱已上傳、已匯出、已通知或已送達。",
    ],
    requiredPermissions: ["clients.read", "occupational_therapy_assessments.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線正式同步尚未設定；不得把本機內容宣稱為已送達、已完成或已簽署。",
  }),
  staffPage(34, "professional-care", "physical-assessment", {
    title: "物理治療評估",
    description: "以人工、非標準化方式保存物理治療量測、觀察、目標、建議及追蹤。",
    primaryActions: ["開始新評估草稿", "建立草稿新版", "簽署評估", "建立更正版"],
    filters: ["個案", "物理治療師", "目前服務狀態", "人工複評期限"],
    metrics: ["已完成評估", "尚未評估", "今日以前到期", "尚未到期"],
    columns: ["個案與服務狀態", "最近評估與治療師", "人工量測", "觀察、目標、建議與追蹤", "人工期限", "操作"],
    acceptance: [
      "第 34 頁使用獨立物理治療資料領域，不得以第 33 頁職能治療評估的資料、權限或版本冒充完成。",
      "每位指派個案只顯示一列，呈現最近評估、目前負責物理治療師、人工輸入複評期限與期限依據。",
      "每項人工量測明確區分精確 decimal 數值文字、觀察文字、缺值及不適用；數值另存人工單位，缺值與不適用各自必填理由，不得互相代換或加總成臨床分數。",
      "第一版固定 manual_unstandardized 與 manual-physical-therapy-v1 技術參照；未提供正式表單或公式時，不得宣稱官方量表、自動診斷、計分或自動期限。",
      "保存人工功能觀察、目標、建議與追蹤計畫；草稿、修訂、簽署與有理由更正全部使用最近 15 分鐘 AAL2、actor-scoped 冪等與不可覆寫線性版本鏈。",
      "只有目前 professional 且具物理治療專用權限者可新增、修訂、簽署或更正；catalog、頁面、API 與資料庫均受機構、分支及指派個案範圍限制。",
      "附件、匯出、提醒與離線正式同步未設定時須 fail closed／not_configured，不得宣稱已上傳、已匯出、已通知或已送達。",
    ],
    requiredPermissions: ["clients.read", "physical_therapy_assessments.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線正式同步尚未設定；不得把本機內容宣稱為已送達、已完成或已簽署。",
  }),
  staffPage(35, "professional-care", "chewing", {
    title: "咀嚼能力評估",
    description: "以人工、未標準化候選欄位保存咀嚼相關觀察，不產生正式能力分級或轉介。",
    primaryActions: ["開始人工觀察草稿", "建立不可變新版", "正式簽署／更正（規則未發布時封鎖）"],
    filters: ["個案", "人工觀察重播狀態", "答案狀態"],
    metrics: ["人工觀察可重播", "重播不完整", "尚未建立", "人工觀察草稿"],
    columns: ["個案與服務狀態", "最近人工觀察草稿", "答案完整度", "候選重播（非正式）", "操作"],
    acceptance: [
      "第一版固定 manual_unstandardized_chewing_observations 與 chewing-manual-observations-candidate-v1；未提供正式工具、題目、授權來源、權重或能力分級時，不得冒充官方或臨床結果。",
      "六項中性人工觀察逐項保存已出現、未出現、缺值或不適用及理由；缺值與不適用不得當作 0，完整時的已出現項目數也不是分數或能力分級。",
      "草稿與新版形成不可覆寫線性版本鏈，保存規則快照、內容雜湊、作者、評估日及當時服務狀態；所有寫入須 professional 專業身分、專頁權限與最近 15 分鐘 AAL2。",
      "正式工具與規則雙人發布前，正式簽署、更正生效、診斷、照顧決策，以及營養／吞嚥轉介均由 API 與資料庫失敗即關閉，且不得自動建立或通知轉介。",
      "所有讀寫受機構、分支及指派個案範圍限制；非法篩選不得放寬清單，附件、匯出、離線同步與通知未配置時不得假成功。",
    ],
    requiredPermissions: ["clients.read", "chewing_assessments.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "離線正式同步尚未設定；不得把本機內容宣稱為已送達、已完成或已簽署。",
  }),
  staffPage(36, "professional-care", "mna", {
    title: "MNA 營養評估",
    description: "追蹤 MNA-SF／完整 MNA 結果、人工期限及後續；電子授權未配置前正式操作失敗即關閉。",
    primaryActions: ["建立評估草稿（授權未配置時封鎖）", "簽署（授權未配置時封鎖）", "建立更正版（授權未配置時封鎖）"],
    filters: ["個案", "風險", "後續追蹤"],
    metrics: ["尚未評估", "正常", "有風險", "待追蹤"],
    columns: ["個案", "篩檢／完整結果", "評估日期", "人工期限與後續", "版本／操作"],
    acceptance: [
      "第 36 頁使用獨立 MNA 資料領域、專頁權限與路由；只載入目前機構、分支及指派個案，非法、陣列或未知篩選不得放寬成全部清單。",
      "MNA-SF、完整 MNA、台灣中文翻譯與電子版均依指定授權版本治理；未取得 Mapi Research Trust／權利人許可、電子實作核准與必要畫面審查前，不得重打、近似重建或嵌入題目、選項、公式及譯文。",
      "授權未配置須與無資料分開顯示；正式草稿、計分、風險分類、簽署、更正及照顧決策由 API 與資料庫 fail closed，合成展示不得寫入或宣稱臨床結果。",
      "取得授權後的正式實作須凍結表單、公式、語言、授權及內容雜湊，篩檢與完整分數、風險、簽署及有理由更正形成不可覆寫線性版本鏈並可重現。",
      "複評期限、期限依據、後續處置、負責人及狀態可追蹤；未發布自動期限或後續規則時只接受明確人工資料，不得自動推論、通知或改變照顧決策。",
      "所有高風險寫入須 professional、clients.read、mna_assessments 專頁權限、最近 15 分鐘同工作階段 AAL2、actor-scoped 冪等鍵及 expected version；授權與 AAL2 必須在讀取內容前驗證。",
      "附件、匯出、離線同步與通知未設定時明示 not_configured，不得宣稱已完成、已送達或已同步。",
    ],
    requiredPermissions: ["clients.read", "mna_assessments.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "正式題本與電子授權尚未配置；離線、附件、匯出及通知均不得假成功。",
  }),
  staffPage(37, "professional-care", "consultations", {
    title: "跨專業照會",
    description: "以不可變事件帳本提出問題、精確指派、回覆、補充、結案與重開。",
    primaryActions: ["提出照會", "指派／改派", "回覆／補充", "結案／重開", "狹義更正"],
    filters: ["個案", "提出人", "承辦人／待指派", "人工專業別", "人工急迫性", "狀態", "期限／缺值／不適用", "關鍵字"],
    metrics: ["完整符合數", "待指派", "進行中", "逾期", "已結案", "期限缺值／不適用"],
    columns: ["個案／專業別", "問題摘要", "提出／承辦", "急迫性／期限", "狀態", "事件與站內通知"],
    acceptance: [
      "建立、指派、改派、回覆、補充、結案、重開與更正皆以 expected sequence 新增事件，不覆寫完成內容。",
      "提出人及精確承辦人均須為目前合格且可存取指定個案的人員；tenant、branch、assigned-client 範圍失敗即拒絕。",
      "專業治理 taxonomy 未發布時只保存人工代碼與名稱並標示 manual_unstandardized；人工急迫性不得被系統推論。",
      "每次轉換建立凍結收件者的站內 queued outbox；外部 provider 未設定時不得宣稱 delivered、read 或 confirmed。",
      "完整統計在 200 筆明細截斷前計算；期限缺值與不適用分開顯示。",
    ],
    requiredPermissions: ["clients.read", "interprofessional_consultations.read"],
    riskLevel: "high",
  }),
  staffPage(38, "professional-care", "case-conferences", {
    title: "個案研討會議",
    description: "以不可變版本保存個案研討、出席、問題、決議、行動、簽署及更正。",
    primaryActions: ["建立草稿", "修訂草稿", "簽署", "有理由更正"],
    filters: ["個案", "狀態", "行動負責人", "行動狀態／逾期", "會議日期", "關鍵字"],
    metrics: ["完整符合數", "草稿", "已簽署", "已更正", "待辦／逾期", "期限缺值／不適用"],
    columns: ["個案／會議", "問題與決議", "出席者快照", "逐項行動", "狀態", "操作與版本歷程"],
    acceptance: [
      "會議綁定精確個案與開始、結束時間；出席者角色與出席狀態、逐項行動負責人及期限三態均凍結為版本快照。",
      "建立、修訂、簽署與有理由更正以 expected version 新增不可變線性版本；簽署後不得原地覆寫。",
      "簽署及更正要求同一工作階段最近 15 分鐘 AAL2，並保存簽署人、角色、重新驗證、伺服器時間及內容雜湊。",
      "catalog、頁面、API 與資料庫同時要求 clients.read 與 case_conferences.read；tenant、branch 與 assigned-client 失敗即拒絕。",
      "人工指定期限不得早於台北會議日期；逾期只依 dated 期限判定，缺值與不適用分開保存、篩選及統計。",
      "附件、通知、匯出、離線及外部 provider 未設定時明示 not_configured，不宣稱外部 delivered、read 或 confirmed。",
      "完整集合統計在 200 筆明細限制前計算；桌機表格與手機卡片使用同一不可變快照。",
    ],
    requiredPermissions: ["clients.read", "case_conferences.read"],
    riskLevel: "high",
  }),
  staffPage(39, "professional-care", "referrals", {
    title: "轉介管理",
    description: "以不可變事件管理草稿、送出、人工收件、回覆、結案與狹義更正。",
    primaryActions: ["建立草稿", "送出", "人工登記收件", "登記回覆", "結案", "狹義更正"],
    filters: ["個案", "接收單位／缺值／不適用", "狀態", "最近事件日期", "關鍵字"],
    metrics: ["符合轉介", "草稿", "已送出", "已收件", "已回覆", "已結案", "接收單位缺值／不適用"],
    columns: ["個案／轉介日", "接收單位", "轉介原因", "負責人／最近事件", "狀態", "事件與站內佇列"],
    acceptance: [
      "建立草稿、送出、人工登記收件、回覆及結案依固定線性狀態追加事件；expected sequence 阻擋過期寫入。",
      "狹義更正必須指定同一轉介的既有非更正事件及理由，且不得改寫原事件或改變目前狀態。",
      "catalog、頁面、API 與資料庫同時要求 clients.read 與 referral_management.read，tenant、branch、assigned-client 失敗即拒絕。",
      "正式接收單位字典未設定時只保存 manual_unstandardized 人工代碼與名稱；缺值與不適用分開保存、篩選及統計。",
      "送出及人工收件不是外部 provider 回執；附件、匯出、外部送達與通知 provider 未設定時明示 not_configured。",
      "完整集合統計在 200 筆明細限制前計算；接收單位、狀態與最近事件日期篩選結果精確。",
    ],
    requiredPermissions: ["clients.read", "referral_management.read"],
    riskLevel: "high",
  }),
  staffPage(40, "professional-care", "physical-services", {
    title: "物理治療服務紀錄",
    description: "以不可變版本保存物理治療服務、個案反應與人工建議。",
    primaryActions: ["新增服務草稿", "建立草稿新版", "簽署紀錄", "建立有理由更正"],
    filters: ["起日", "迄日", "個案", "物理治療師", "紀錄狀態", "關鍵字"],
    metrics: ["今日服務", "草稿待簽", "已簽署", "已簽更正版", "連結最近有效評估"],
    columns: ["個案／狀態", "發生時間／治療師", "內容／反應／建議", "唯讀評估參照", "版本／操作"],
    acceptance: [
      "第 40 頁使用獨立服務紀錄領域；第 34 頁最近已簽或已更正評估只能由伺服器選取並凍結為唯讀參照，不共用版本或寫入權限。",
      "服務內容、個案反應與人工建議各自明確區分已記錄、缺值及不適用；缺值與不適用必須保存不同狀態與理由。",
      "草稿、草稿新版、簽署及有理由更正形成 append-only 線性版本；已簽紀錄禁止直接更新或刪除，只能建立連回前版的更正版。",
      "簽署與更正要求最近 15 分鐘同 session AAL2；所有寫入使用 actor-scoped idempotency、expected version 及 strict action／receipt correlation。",
      "catalog、頁面、API 與資料庫同時要求 clients.read 與 physical_therapy_services.read，並重驗 tenant、branch、assigned-client、professional 及動作權限。",
      "不推論治療公式、診斷或自動建議；附件、匯出及離線未治理時明示 not_configured 並 fail closed。",
      "完整集合統計在 200 筆明細限制前計算；桌機表格與手機卡片使用同一不可變快照。",
    ],
    requiredPermissions: ["clients.read", "physical_therapy_services.read"],
    riskLevel: "high",
  }),
  staffPage(41, "professional-care", "occupational-services", {
    title: "職能治療服務紀錄",
    description: "以不可變版本保存職能治療服務、個案反應與人工建議。",
    primaryActions: ["新增服務草稿", "建立草稿新版", "簽署紀錄", "建立有理由更正"],
    filters: ["起日", "迄日", "個案", "職能治療師", "紀錄狀態", "關鍵字"],
    metrics: ["今日服務", "草稿待簽", "已簽署", "已簽更正版", "連結最近有效評估"],
    columns: ["個案／狀態", "發生時間／治療師", "內容／反應／建議", "唯讀評估參照", "版本／操作"],
    acceptance: [
      "第 41 頁使用獨立服務紀錄領域；第 33 頁最近已簽或已更正評估只能由伺服器選取並凍結為唯讀參照，不共用版本或寫入權限。",
      "服務內容、個案反應與人工建議各自明確區分已記錄、缺值及不適用；缺值與不適用必須保存不同狀態與理由。",
      "草稿、草稿新版、簽署及有理由更正形成 append-only 線性版本；已簽紀錄禁止直接更新或刪除，只能建立連回前版的更正版。",
      "簽署與更正要求最近 15 分鐘同 session AAL2；所有寫入使用 actor-scoped idempotency、expected version 及 strict action／receipt correlation。",
      "catalog、頁面、API 與資料庫同時要求 clients.read 與 occupational_therapy_services.read，並重驗 tenant、branch、assigned-client、professional 及動作權限。",
      "不推論治療公式、診斷或自動建議；附件、匯出及離線未治理時明示 not_configured 並 fail closed。",
      "完整集合統計在 200 筆明細限制前計算；桌機表格與手機卡片使用同一不可變快照。",
    ],
    requiredPermissions: ["clients.read", "occupational_therapy_services.read"],
    riskLevel: "high",
  }),
  staffPage(42, "professional-care", "service-summary", {
    title: "專業服務彙整表",
    description: "以同一不可變快照按年月彙整已授權個案的專業工作與來源證據。",
    primaryActions: ["查看來源", "切換月份", "匯出彙整"],
    filters: ["年月", "個案", "專業別", "狀態"],
    metrics: ["應完成", "已完成", "待完成", "逾期"],
    columns: ["個案", "專業別", "評估狀態", "服務次數", "最近日期", "下次期限", "狀態"],
    acceptance: [
      "畫面指標、300 筆有界明細及 CSV 匯出使用同一個 actor-scoped、雜湊保護、15 分鐘有效的資料庫快照，總數不得各自重算。",
      "每個項目以文字呈現已完成、待完成、逾期或規則未設定；狀態不得只靠顏色，並可連回第 33–41 頁的實際來源。",
      "tenant、branch、clients.read、summary permission、來源頁權限及 assigned-client 範圍逐層重驗；無權限來源不進入統計或明細。",
      "應完成只計已有權威來源的工作單位；不得把尚未建立的評估、未設定服務頻率或缺值推測為 0 或已完成。",
      "第 35 頁正式規則仍是 candidate_only，第 36 頁電子化授權仍是 license_required_not_configured；兩者明示治理缺口且不列為正式完成。",
      "匯出要求最近 15 分鐘 AAL2、同一使用者／機構／分支及未過期快照，並留下不含姓名、篩選值或內容的稽核紀錄。",
    ],
    requiredPermissions: ["clients.read", "professional_service_summary.read"],
    riskLevel: "sensitive",
    offlineMode: "online-only",
    offlineNote: "專業服務彙整、來源明細與 CSV 快照含敏感照顧資訊，不保存於離線快取。",
  }),

  staffPage(43, "communication", "care-communication", {
    title: "溝通紀錄",
    description: "保存照顧溝通、家屬授權快照、待送證據與不可變更正歷程。",
    primaryActions: ["新增待送紀錄", "建立更正"],
    filters: ["個案", "日期", "作者", "傳送狀態", "確認狀態"],
    metrics: ["符合版本", "訊息主線", "更正版", "目前待送", "今日建立", "可信附件"],
    columns: ["版本／時間", "個案／作者", "訊息內容", "家屬授權快照", "附件／回條狀態", "操作"],
    acceptance: [
      "只顯示 care_communication 類別，不得混入顧問訊息；機構、分支、個案指派及有效 messages.read 家屬同意均須精確相符。",
      "保存作者、發生／送出時間、收件授權快照、附件三態、待送事件與不可變更正鏈；所有寫入使用 actor-scoped 冪等鍵及可核對完成憑證。",
      "家屬端收件、provider worker、離線 consumer 與附件掃毒未設定時，畫面與 API 明示 not_configured／queued，不得宣稱 delivered、read 或 confirmed。",
    ],
    requiredPermissions: ["care_communications.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "家屬收件與離線 consumer 尚未設定；本頁僅可在線上讀取受稽核快照與建立正式不可變紀錄。",
  }),
  staffPage(44, "communication", "calendar", {
    title: "安心行事曆",
    description: "以同一不可變快照管理照顧行程、活動與取消版本。",
    primaryActions: ["發布行程", "建立更正版", "建立取消版本"],
    filters: ["月份", "機構", "分類", "狀態", "今日", "關鍵字"],
    metrics: ["本月行程", "今日行程", "即將開始", "已取消"],
    columns: ["行程／版本", "開始時間", "結束時間", "地點", "對象", "負責人", "分類", "狀態"],
    acceptance: [
      "月曆與列表直接使用同一不可變 snapshot.items，事件集合、狀態與取消原因完全一致。",
      "事件保存時間、地點、對象及負責人；發布、更正及取消只新增版本，取消必填理由且不得改寫既有版本。",
      "機構、分支、角色及個案資料範圍均 fail closed；所有寫入要求近期 AAL2、actor-scoped 冪等鍵及可核對完成憑證。",
      "外部通知與電子簽署未設定時明示 not_configured／none_not_sent，不得宣稱已送達或已簽署。",
    ],
    requiredPermissions: ["reassurance_calendar.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "本頁不把正式行程或寫入操作保存於裝置；重新連線後須重新取得單一伺服器快照。",
  }),
  staffPage(45, "communication", "push-notifications", {
    title: "推播通知",
    description: "依對象發送或排程系統及家屬通知。",
    primaryActions: ["建立推播", "預覽收件者", "排程發送", "重試失敗"],
    filters: ["分類", "對象", "排程日期", "發送狀態"],
    metrics: ["排程中", "已送達", "部分失敗", "已取消"],
    columns: ["主旨", "分類", "對象", "收件人數", "排程時間", "發送狀態", "建立者"],
    acceptance: ["發送前顯示實際收件者，部分失敗只重試失敗者且不重送已成功者。"],
    requiredPermissions: ["notifications.manage"],
    riskLevel: "high",
  }),

  staffPage(46, "service-management", "attendance", {
    title: "出勤管理",
    description: "記錄個案簽到、簽退、補登及主管審查。",
    primaryActions: ["簽到", "簽退", "建立補登", "主管審查"],
    filters: ["日期", "分支", "個案", "出勤狀態", "補登狀態"],
    metrics: ["應到", "已到", "未到", "待簽退", "待審補登"],
    columns: ["個案", "簽到時間", "簽退時間", "來源", "服務時數", "補登", "狀態"],
    acceptance: ["重複簽到與負時數被阻擋；補登保存理由、原值、新值及主管審查。"],
    requiredPermissions: ["clients.read", "attendance.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(47, "service-management", "transport-plans", {
    title: "交通趟次計畫",
    description: "規劃個案接送、車輛、駕駛、地點與時間。",
    primaryActions: ["建立趟次", "安排車輛", "發布計畫", "通知異動"],
    filters: ["日期", "分支", "方向", "車輛", "駕駛", "狀態"],
    metrics: ["趟次數", "乘客數", "容量衝突", "待發布"],
    columns: ["趟次", "方向", "車輛", "駕駛", "乘客", "預計時間", "狀態"],
    acceptance: [
      "每個趟次凍結車輛、駕駛、逐人上下車點、預計時間、乘員與機構規則版本。",
      "人員、車輛、時間與容量衝突逐項顯示且不可靜默通過；無衝突發布也必須由非建立人獨立核准。",
      "有衝突趟次禁止一般發布，只有另一位具 override 權限且最近 15 分鐘 AAL2 的人員寫明理由後才能例外發布。",
      "外部通知、匯出及 24 小時唯讀快取未配置時明示 not_configured，不得宣稱已送達、可下載或可離線。",
    ],
    requiredPermissions: ["clients.read", "transport_plans.read"],
    riskLevel: "high",
    offlineMode: "read-cache-24h",
    offlineNote: "24 小時唯讀快取尚未配置；正式交通與個案位置資料不得寫入離線儲存。",
  }),
  staffPage(48, "service-management", "transport-execution", {
    title: "接送執行紀錄",
    description: "依交通計畫記錄實際上下車時間與例外。",
    primaryActions: ["開始趟次", "記錄上下車", "登記例外", "完成趟次"],
    filters: ["日期", "車輛", "駕駛", "完成狀態", "例外狀態"],
    metrics: ["待執行", "進行中", "已完成", "遲到", "未配對"],
    columns: ["個案", "計畫趟次", "實際上車", "實際下車", "駕駛", "例外", "狀態"],
    acceptance: [
      "每個執行事件凍結精確已發布原計畫版本與雜湊；同一趟次只能開始一個執行版本，不能改綁草稿、舊版或其他分支計畫。",
      "開始、逐人上車、逐人下車、人工例外與完成形成不可變順序鏈；全部乘客已成對或有具名人工處置前禁止完成。",
      "遲到固定以實際開始晚於原計畫開始計算，不套用未發布寬限；未完成、遲到、有例外與未配對皆由同一快照篩選並與明細一致。",
      "駕駛只可操作自己被指派的趟次；跨駕駛操作須 manage_any，例外處置與完成另需最近 15 分鐘同 session AAL2。",
      "外部通知、匯出與 24 小時離線草稿同步未配置時明示 not_configured，不得宣稱已送達、可下載或可離線。",
    ],
    requiredPermissions: ["clients.read", "transport_execution.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
    offlineNote: "24 小時離線草稿同步尚未配置；正式接送事件不得寫入離線儲存。",
  }),
  staffPage(49, "service-management", "claims", {
    title: "申報管理",
    description: "驗證、輸出、提交及對帳長照服務申報。",
    primaryActions: ["驗證申報", "建立快照", "匯出檔案", "匯入回覆", "完成對帳"],
    filters: ["服務月份", "分支", "個案", "申報狀態", "錯誤類型"],
    metrics: ["申報筆數", "申報金額", "待修正", "退件", "已對帳"],
    columns: ["個案", "服務日期", "服務代碼", "數量", "金額", "證據", "申報狀態"],
    acceptance: ["僅完成且證據齊全的服務可申報，重複服務被阻擋並可追溯不可變快照。"],
    requiredPermissions: ["claims.read"],
    riskLevel: "high",
  }),
  staffPage(50, "service-management", "case-service-records", {
    title: "個案服務紀錄",
    description: "建立符合法定必要欄位的個案服務紀錄。",
    primaryActions: ["新增紀錄", "上傳附件", "簽署", "建立更正"],
    filters: ["個案", "服務日期", "服務類型", "執行人", "簽署狀態"],
    metrics: ["服務筆數", "待完成", "待簽署", "已更正"],
    columns: ["個案", "服務日期", "服務類型", "內容", "執行人", "附件", "簽署"],
    acceptance: ["缺少必要欄位不得完成；簽署後更正必須產生帶有原紀錄連結的新版本。"],
    requiredPermissions: ["clients.read", "case_service_records.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(51, "service-management", "nursing-assessment", {
    title: "護理評估",
    description: "護理人員保存人工非標準化觀察、問題、措施、反應與複評日期；不提供官方分數或風險。",
    primaryActions: ["新增草稿", "修訂草稿", "比較版本", "簽署", "建立更正版"],
    filters: ["個案"],
    metrics: ["可見個案", "已載入版本", "截斷提示"],
    columns: ["個案", "觀察", "問題", "措施", "反應", "人工複評日", "版本", "簽署"],
    acceptance: ["缺少適用必填不得簽署，歷次評估可比較且仍以原表單版本重算。"],
    riskLevel: "high",
    requiredPermissions: ["clients.read", "nursing_assessments.read"],
  }),
  staffPage(52, "service-management", "client-service-plans", {
    title: "個案服務計畫",
    description: "管理服務目標、措施、頻率、負責人與檢討。",
    primaryActions: ["建立計畫", "送審", "核准計畫", "建立新版本"],
    filters: ["個案", "生效狀態", "負責人", "檢討期限"],
    metrics: ["有效計畫", "待審核", "即將檢討", "已到期"],
    columns: ["個案", "版本", "目標", "措施", "負責人", "生效日", "檢討日", "狀態"],
    acceptance: ["核准版本凍結，後續調整建立新版本且保留前版目標與措施。"],
    requiredPermissions: ["clients.read", "care_plans.read"],
    riskLevel: "high",
  }),
  staffPage(53, "service-management", "service-usage", {
    title: "服務使用紀錄",
    description: "記錄實際服務項目、執行人、結果及取消。",
    primaryActions: ["新增服務", "取消服務", "完成簽署"],
    filters: ["日期", "個案", "服務項目", "執行人", "狀態"],
    metrics: ["已排服務", "已完成", "已取消", "資格異常"],
    columns: ["個案", "日期", "時段", "服務項目", "執行人", "結果", "狀態"],
    acceptance: ["執行人資格在服務時間有效；已完成紀錄可作申報來源並保持可追溯。"],
    requiredPermissions: ["clients.read", "services.read"],
    riskLevel: "high",
    offlineMode: "draft-sync-24h",
  }),
  staffPage(54, "service-management", "daily-summary", {
    title: "每日服務彙整",
    description: "以單一不可變資料庫快照彙整當日八類授權來源與下鑽證據。",
    primaryActions: ["查看來源", "切換日期", "匯出彙整"],
    filters: ["日期", "分支", "個案", "資料完整度"],
    metrics: ["出勤", "量測完成", "活動參與", "餐食", "交通", "異常"],
    columns: ["個案", "出勤", "生命徵象", "活動", "餐食", "交通", "異常", "完整度"],
    acceptance: [
      "畫面、每格證據與 CSV 重新取得同一個 actor-scoped、branch-scoped、雜湊保護且 15 分鐘有效的單一資料庫陳述式快照，不得以多個前端查詢拼裝。",
      "八個來源各自以 read permission、assigned-client 與來源專屬可見性重驗；交通另維持 assigned driver 或 manage_any 邊界。",
      "未授權或未配置來源顯示 unknown 且數量為空，不得以 0 補值；完整度分母只納入可讀且已配置來源。",
      "每格只連至白名單內部來源頁，並在快照中保存有界來源 ID 與來源雜湊；餐食與接送舊頁若僅支援日期篩選，不宣稱精確個案定位。",
      "CSV 匯出要求最近 15 分鐘同工作階段 AAL2，並重新驗證快照擁有者、機構、分支、個案與所有已揭露來源權限。",
      "24 小時離線唯讀快取尚未配置時明示 not_configured；展示模式只使用合成唯讀快照。",
    ],
    requiredPermissions: ["clients.read", "daily_service_summary.read"],
    riskLevel: "sensitive",
    offlineMode: "online-only",
    offlineNote: "24 小時離線唯讀快取尚未配置；每日彙整與來源證據僅可連線查閱。",
  }),
  staffPage(55, "service-management", "approved-care-plans", {
    title: "核定照顧計畫",
    description: "保存中央核定計畫、服務限制、額度與版本。",
    primaryActions: ["查看計畫", "比較版本", "確認超額警示"],
    filters: ["個案", "核定日期", "生效狀態", "來源"],
    metrics: ["有效計畫", "即將到期", "超出計畫", "待確認"],
    columns: ["個案", "來源", "核定日", "生效期間", "服務限制", "額度", "版本", "狀態"],
    acceptance: [
      "中央核定版本不可覆寫；超出計畫或額度的服務顯示警示並要求理由。",
      "讀取採單一陳述式、機構／分支／指派個案限定快照；頁面、完整版本歷程、來源、差異與統計使用相同資料範圍。",
      "流程鏈尾、發布鏈尾與指定日期有效版本分開呈現；未完成草稿及未來生效版本不提前取代當期已簽版本。",
      "未知原始欄位完整保留為有界且雜湊驗證的純文字，不執行 HTML；缺值不當 0，未映射欄位不得冒充正式額度或申報規則。",
      "正式來源發布、欄位映射與超限交易未配置時明示未完成；一般查閱要求員工 AAL2，但不要求高風險操作專用的近期重新驗證。",
    ],
    requiredPermissions: ["clients.read", "care_plans.read"],
    riskLevel: "high",
    offlineMode: "online-only",
    offlineNote: "核定正式來源與完整原始欄位不可離線快取；離線或快照過期須提示重新連線更新。",
  }),
  staffPage(56, "service-management", "feedback-complaints", {
    title: "意見與申訴",
    description: "受理、分級、處理、追蹤及結案意見與申訴。",
    primaryActions: ["建立案件", "指派承辦", "更新處理", "完成結案"],
    filters: ["案件日期", "來源", "類型", "風險", "承辦人", "狀態"],
    metrics: ["案件數", "高風險", "處理中", "逾期"],
    columns: ["案件編號", "來源", "類型", "風險", "承辦人", "期限", "狀態"],
    acceptance: [
      "案件有唯一編號與期限，高風險或逾期自動升級且敏感內容依權限遮蔽。",
      "受理期限只能來自已發布的精確版本規則；沒有正式規則時 UI、API 與資料庫皆失敗即關閉。",
      "狀態、指派、更正與結案只追加不可變事件，操作綁定預期版本及冪等鍵；更正不覆寫原內容，結案要求最近 15 分鐘同工作階段 AAL2。",
      "敏感敘述由資料庫依 complaints.sensitive 回傳或遮蔽，查閱與每次寫入皆保留稽核。",
    ],
    requiredPermissions: ["complaints.read"],
    riskLevel: "high",
    offlineMode: "online-only",
  }),
  staffPage(57, "service-management", "meals", {
    title: "餐食管理",
    description: "管理菜單、餐別、質地、過敏禁忌及份數。",
    primaryActions: ["建立菜單", "設定餐食", "確認衝突", "完成備餐"],
    filters: ["日期", "餐別", "質地", "過敏警示", "分支"],
    metrics: ["預計份數", "實際份數", "特殊質地", "過敏衝突"],
    columns: ["個案", "餐別", "菜單", "質地", "過敏／禁忌", "份數", "狀態"],
    acceptance: ["過敏、禁忌與餐點衝突即時警示，實際份數可與當日出勤逐人對帳。"],
    requiredPermissions: ["clients.read", "attendance.read", "health.read", "meals.read"],
    riskLevel: "high",
    offlineMode: "read-cache-24h",
  }),

  staffPage(58, "operations", "organization", {
    title: "機構資料",
    description: "以不可變提案與獨立核准管理機構許可、服務、費率、容量、聯絡及生效版本。",
    primaryActions: ["建立完整異動提案", "獨立核准或駁回", "查看版本歷程"],
    filters: ["分支", "版本狀態", "生效日期"],
    metrics: ["有效版本", "待審異動", "許可到期", "容量"],
    columns: ["機構／分支", "許可字號", "服務類型", "容量", "生效日", "版本", "狀態"],
    acceptance: [
      "所有異動先凍結完整提案，且只能由不同授權人員在最近 15 分鐘 AAL2 下核准或駁回。",
      "有效終端期間不得重疊；更正建立新版本，歷史許可、精確費率文字、容量與聯絡資料不可被覆寫。",
      "正式代碼、到期提醒、附件、匯出與主管機關同步未配置時明示未設定或停用，不得臆測法規或費率。",
    ],
    requiredPermissions: ["organization_profile.read"],
    riskLevel: "high",
  }),
  staffPage(59, "operations", "staff", {
    title: "員工管理",
    description: "以既有身分主檔及不可變提案管理聘僱、職務、角色與離職停用。",
    primaryActions: ["建立聘僱異動提案", "建立離職停用提案", "角色異動送審", "獨立審核", "查看第 72 頁證照"],
    filters: ["聘僱狀態", "角色", "證照終端事實", "關鍵字"],
    metrics: ["在職員工", "有明確過期證照", "非啟用帳號", "待審異動"],
    columns: ["員工／版本", "職務", "角色", "證照終端事實", "到職日", "帳號／撤銷回執"],
    acceptance: [
      "profiles、memberships 與 membership_roles 是唯一身分與角色來源；本頁不另建平行員工主檔，角色異動沿用第 81 頁治理，證照只讀取第 72 頁終端投影。",
      "聘僱、角色及立即離職採不可變提案、預期員工版本、使用者範圍冪等鍵與不同人審核；權限擴張及離職均須同工作階段最近 15 分鐘 AAL2。",
      "離職核准原子更新本系統 membership 並建立 5 分鐘期限的撤銷工作；Supabase Auth Admin 供應商未配置前只標示 not_configured／not_verified，不得宣稱遠端工作階段已撤銷或 SLA 已驗證。",
      "組織範圍候選／邀請來源與 Auth 建立未配置時 onboarding 在 API 與資料庫 fail closed，頁面不得掃描全域 profiles 或提供到職建立控制。",
      "資格 30 日提醒與受限制服務規則未發布時明示 not_configured／not_evaluated，不推算即將到期、醫療結論或服務阻擋；附件、匯出、離線及完整 HR／薪資均停用或排除。",
      "受治理 action header、機構／分支／欄位權限及近期 AAL2 都在解析敏感 body 前驗證；快照與嚴格回執不得接受跨租戶、跨分支或版本漂移。",
    ],
    requiredPermissions: ["staff_management.read", "staff_management.identity.read",
      "staff_management.employment.read", "staff_management.roles.read",
      "staff_management.qualifications.read", "staff_certificates.read"],
    riskLevel: "high",
  }),
  staffPage(60, "operations", "clients", {
    title: "個案基本資料",
    description: "管理個案身分、關係人、資格、健康及同意。",
    primaryActions: ["新增個案", "更新資料", "管理關係人", "管理同意"],
    filters: ["分支", "服務狀態", "負責人", "資格", "關鍵字"],
    metrics: ["有效個案", "資格即將到期", "缺同意", "重複警示"],
    columns: ["個案", "分支", "服務狀態", "主要聯絡人", "資格", "負責人", "警示"],
    acceptance: ["穩定識別碼重複時阻擋，敏感欄位依角色遮罩且查閱留下稽核。"],
    requiredPermissions: ["clients.read"],
    riskLevel: "high",
  }),
  staffPage(61, "operations", "client-transitions", {
    title: "收案／異動／結案",
    description: "管理收案、暫停、恢復、轉出、結案與死亡事件。",
    primaryActions: ["建立收案", "暫停服務", "恢復服務", "轉出", "結案"],
    filters: ["分支", "異動類型", "生效日期", "狀態", "個案"],
    metrics: ["本月收案", "暫停服務", "本月結案", "待交接"],
    columns: ["個案", "異動類型", "生效日期", "理由", "交接", "建立者", "狀態"],
    acceptance: ["所有狀態異動保存生效日、理由與交接，不得刪除或重寫個案生命週期。"],
    requiredPermissions: ["clients.read"],
    riskLevel: "high",
  }),
  staffPage(62, "operations", "document-printing", {
    title: "文件列印",
    description: "依核准範本產生、預覽、列印及下載文件。",
    primaryActions: ["選擇範本", "預覽文件", "產生 PDF", "列印／下載"],
    filters: ["文件類型", "範本版本", "日期", "個案"],
    metrics: ["目前核准範本", "範圍內個案", "不可變文件工作", "PDF 產生器狀態"],
    columns: ["文件", "個案", "範本版本", "資料日期", "產生者", "產生時間", "預覽／下載授權"],
    acceptance: ["預覽與 PDF 使用同一不可變模型；範本版本、水印、內容雜湊、產生及每次預覽／下載授權均留稽核。正式範本、私有中文字型或短效簽章未配置時須明示並停止產生，不得猜測官方表單。"],
    requiredPermissions: ["clients.read", "document_printing.read"],
    riskLevel: "high",
  }),
  staffPage(63, "operations", "smart-scheduling", {
    title: "智慧排班",
    description: "以已發布人工規則輔助排班並保留可解釋衝突；不使用 AI。",
    primaryActions: ["建立規則檢查草稿", "查看衝突依據", "獨立覆核", "發布無衝突班表"],
    filters: ["日期區間", "分支", "員工", "職類", "衝突狀態"],
    metrics: ["排定班次", "未填班次", "工時衝突", "資格衝突", "容量衝突"],
    columns: ["日期", "班別", "分支", "員工", "職類", "服務需求", "衝突", "狀態"],
    acceptance: [
      "資格只讀第 72 頁終端證照投影；工時、休息、場地、車輛與容量只採機構已發布且期間唯一的 manual_unstandardized 規則，未配置即 fail closed。",
      "每項衝突保存規則版本、精確觀察值與說明；一般發布不得接受衝突，也不得以 AI、自動排班或自動發布名義靜默通過。",
      "衝突覆核須由非建立人的獨立授權人員，以最近 15 分鐘同工作階段 AAL2 及理由建立不可變決議版本；建立、更正與決議均使用預期版本及 actor-scoped 冪等回執。",
      "機構／分支／人員範圍與 staff_scheduling、staff_certificates 權限在 API 與資料庫雙重驗證；直接表寫入、匯出及離線均拒絕。",
    ],
    requiredPermissions: ["staff_scheduling.read", "staff_certificates.read"],
    riskLevel: "high",
  }),
  staffPage(64, "operations", "billing", {
    title: "帳務管理",
    description: "以核准生效費目管理內部帳單、離線付款紀錄、退款、調整、欠款與每日對帳。",
    primaryActions: ["建立帳單", "登記離線付款", "建立內部收據紀錄", "退款／調整", "每日對帳"],
    filters: ["帳務期間", "分支", "個案", "付款狀態", "費目"],
    metrics: ["應收", "已收", "欠款", "退款", "對帳差異"],
    columns: ["個案", "帳單期間", "帳單編號", "應收", "已收", "餘額", "付款狀態"],
    acceptance: [
      "帳單只能引用期間唯一的核准費目版本，並固定精確 decimal 單價與明示稅務狀態；未配置費率、稅務或官方文件規則時以 not_configured fail closed，不臆測費率、稅額或法定編號。",
      "帳單、離線付款、退款、調整與內部非稅務收據均為不可變流水；退款連結原付款，調整必填理由，禁止負餘額，預期帳單與分支版本不符即拒絕。",
      "所有寫入綁定機構、分支、actor-scoped 冪等鍵及同工作階段最近 15 分鐘 AAL2；RLS 與資料庫函式再次核權，直接表寫入拒絕。",
      "每日對帳固定分支流水版本，帳單明細餘額、不可變流水餘額與差異可重現；畫面、明細與統計共用單一資料庫快照。",
      "第一版線上付款、卡號輸入、自動扣款、法定收據／發票與匯出均停用；只允許人員登記系統外完成的現金、銀行轉帳或其他離線付款事實。",
    ],
    requiredPermissions: ["billing.read"],
    riskLevel: "high",
  }),
  staffPage(65, "operations", "external-health-devices", {
    title: "外部健康設備",
    description: "接收並管理外部健康設備量測與配對。",
    primaryActions: ["配對設備", "修正未配對", "停用設備", "查看資料"],
    filters: ["設備", "個案", "資料日期", "配對狀態", "連線狀態"],
    metrics: ["符合設備", "符合量測", "未配對資料", "來源去重結果"],
    columns: ["設備", "個案", "量測類型", "來源時間", "接收時間", "數值／單位", "配對狀態"],
    acceptance: ["來源時間與接收時間分開保存，重複資料去重且未配對資料可受控修正。"],
    requiredPermissions: ["external_health_devices.read"],
    riskLevel: "high",
  }),
  staffPage(66, "operations", "hand-hygiene", {
    title: "洗手管理",
    description: "彙整員工洗手設備事件及達成率。",
    primaryActions: ["查看事件", "修正未配對", "查看公式", "匯出"],
    filters: ["日期", "分支", "員工", "設備", "配對狀態"],
    metrics: ["洗手次數", "應執行次數", "達成率", "未配對"],
    columns: ["員工", "設備", "事件時間", "來源", "配對狀態", "修正人", "狀態"],
    acceptance: ["設備事件冪等去重，達成率的分子、分母及排除規則可下鑽查明。"],
    requiredPermissions: ["hand_hygiene.read"],
    riskLevel: "sensitive",
  }),
  staffPage(67, "operations", "notifications", {
    title: "通知中心",
    description: "集中管理工作、警示、重大通知及確認。",
    primaryActions: ["查看來源", "標示已讀", "確認重大通知", "清除篩選"],
    filters: ["未讀", "分類", "優先度", "日期", "關鍵字"],
    metrics: ["未讀", "重大未確認", "今日通知", "逾期"],
    columns: ["時間", "分類", "優先度", "主旨", "來源", "確認期限", "狀態"],
    acceptance: ["每則通知可回到正確來源，重大通知要求確認並在逾時後依規則升級。"],
    requiredPermissions: ["notifications.read"],
    riskLevel: "sensitive",
    offlineMode: "read-cache-24h",
  }),
  staffPage(68, "operations", "announcements", {
    title: "公告管理",
    description: "建立、排程、發布、撤回及追蹤公告已讀。",
    primaryActions: ["建立公告", "預覽對象", "排程發布", "撤回"],
    filters: ["分支", "發布狀態", "對象", "日期", "關鍵字"],
    metrics: ["草稿", "排程中", "已發布", "已到期", "未讀人數"],
    columns: ["標題", "對象", "發布時間", "到期時間", "已讀率", "版本", "狀態"],
    acceptance: ["草稿、排程、發布與到期狀態正確，修改產生版本且撤回必須填理由。"],
    requiredPermissions: ["announcements.read"],
    riskLevel: "sensitive",
  }),
  staffPage(69, "operations", "staff-vital-signs", {
    title: "員工生命徵象",
    description: "受限管理員工健康量測、缺值、不適用與不可變歷程。",
    primaryActions: ["新增量測", "建立更正", "追加作廢版本", "查看趨勢"],
    filters: ["分支", "員工", "量測類型", "值狀態", "發生日期", "搜尋"],
    metrics: ["已量紀錄", "缺值紀錄", "不適用", "門檻警示（未設定）"],
    columns: ["員工", "發生時間", "量測類型", "精確值／單位", "來源／備註", "規則／版本"],
    acceptance: ["明細只由獨立 staff_health 權限與近期 AAL2 查閱；decimal 文字精度完整保留，缺值與不適用分開。機構門檻版本未發布時明示未設定且不產生警示、診斷或建議；趨勢與清單使用同一快照。"],
    requiredPermissions: ["staff_health.read"],
    riskLevel: "high",
  }),
  staffPage(70, "operations", "reports", {
    title: "統計報表",
    description: "以日期與月份開啟有權限的來源彙整，沿用来源快照；自訂統計與本頁直接匯出尚未啟用。",
    primaryActions: ["套用期間", "開啟每日服務彙整", "開啟專業服務彙整表", "查看來源口徑"],
    filters: ["每日日期", "每月月份"],
    metrics: ["來源查閱權限（非業務統計）"],
    columns: ["來源彙整", "期間", "查閱權限", "來源口徑"],
    acceptance: ["報表標示期間、來源、公式與更新時間，畫面、明細及匯出使用同一快照。"],
    riskLevel: "high",
    requiredPermissions: ["reports.read"],
  }),
  staffPage(71, "operations", "training", {
    title: "教育訓練",
    description: "追蹤員工訓練、時數、積分、證明與規則進度。",
    primaryActions: ["新增訓練", "上傳證明", "查看積分", "匯出紀錄"],
    filters: ["年度", "分支", "員工", "課程類型", "到期狀態"],
    metrics: ["完成時數", "有效積分", "即將到期", "缺口人數"],
    columns: ["員工", "課程", "日期", "類型", "時數", "積分", "證明", "狀態"],
    acceptance: ["六年 120 點等進度依選定規則版本計算，可列出每名員工的缺口與到期。"],
    requiredPermissions: ["staff_training.read"],
    riskLevel: "sensitive",
  }),
  staffPage(72, "operations", "staff-certificates", {
    title: "員工證照",
    description: "管理專業證照、登錄、生效、到期與證明。",
    primaryActions: ["新增證照", "上傳證明", "核驗", "申請例外"],
    filters: ["分支", "員工", "證照類型", "效期狀態"],
    metrics: ["有效證照", "即將到期（依已發布規則）", "已過期", "待核驗"],
    columns: ["員工", "證照類型", "證號", "生效日", "到期日", "登錄", "狀態"],
    acceptance: ["證照有效性提供精確投影；受限制服務規則未發布時明示未設定。有限例外須兩名獨立授權人員以近期 AAL2 核准，申請人不得自批。"],
    requiredPermissions: ["staff_certificates.read"],
    riskLevel: "high",
  }),
  staffPage(73, "operations", "staff-vaccinations", {
    title: "員工疫苗",
    description: "受限管理員工疫苗、劑次、批號、院所與證明。",
    primaryActions: ["新增紀錄", "建立更正", "追加作廢版本"],
    filters: ["分支", "員工", "疫苗", "劑次", "日期", "重複警示"],
    metrics: ["接種筆數", "缺證明", "重複警示", "本月新增"],
    columns: ["員工", "疫苗", "劑次", "日期", "批號", "院所", "證明"],
    acceptance: ["同一員工、疫苗與劑次重複時列出可解釋警示並保留各筆，不自動合併。明細只由獨立 staff_health 權限及 AAL2 查閱；附件與提醒未配置時明示未設定。"],
    requiredPermissions: ["staff_health.read"],
    riskLevel: "high",
  }),
  staffPage(74, "operations", "staff-tocc", {
    title: "員工 TOCC",
    description: "受限管理員工 TOCC 結果、效期、證明與處置。",
    primaryActions: ["新增紀錄", "建立更正", "追加作廢版本"],
    filters: ["分支", "員工", "人工效期", "人工異常標記", "處置狀態", "評估日期"],
    metrics: ["人工效期內", "即將到期（未設定）", "人工效期已過", "人工標記待處置"],
    columns: ["員工", "填報日", "有效至", "結果", "證明", "處置", "狀態"],
    acceptance: ["人工有效至逾期與人工異常／positive-like 標記形成可解釋提示，不解析結果或自動診斷。以獨立 staff_tocc 權限、AAL2、人員範圍限制明細並最小化稽核每次查閱；效期規則、提醒及附件未配置時明示未設定。"],
    requiredPermissions: ["staff_tocc.read"],
    riskLevel: "high",
  }),
  staffPage(75, "operations", "meetings", {
    title: "會議管理",
    description: "管理機構會議、決議、行動與期限。",
    primaryActions: ["建立會議", "記錄決議", "指派行動", "簽署會議"],
    filters: ["日期", "分支", "會議類型", "行動狀態"],
    metrics: ["會議數", "待簽署", "行動待辦", "逾期行動"],
    columns: ["會議", "日期", "出席者", "決議", "行動負責人", "期限", "狀態"],
    acceptance: ["出席、議程、決議與行動完整；簽署後版本化且逾期行動形成待辦。"],
    riskLevel: "sensitive",
    requiredPermissions: ["meetings.read"],
  }),
  staffPage(76, "operations", "consultant-messages", {
    title: "顧問訊息",
    description: "以獨立入口管理顧問類別的不可變系統內訊息與實際回條。",
    primaryActions: ["新增訊息", "標示已讀", "確認訊息"],
    filters: ["顧問", "起迄日期", "已讀／確認狀態", "關鍵字"],
    metrics: ["符合訊息", "實際未讀", "今日訊息", "可信附件", "待確認"],
    columns: ["發生／發布時間", "作者", "主旨與內容", "顧問收件快照", "已讀／確認", "操作"],
    acceptance: [
      "獨立入口只接受並顯示 consultant 類別，禁止混入一般訊息或跨機構、跨分支、非收件人資料。",
      "內容、作者、時間與顧問收件者快照不可覆寫；已讀及確認使用可核對、冪等的追加式回條。",
      "每次查閱只留下最小化稽核；未配置可信上傳與掃描管線時，UI/API 明確以 not_configured 拒絕附件。",
      "第一版僅為系統內訊息，不宣稱 LINE、簡訊、Email、PWA 或其他外部送達。",
    ],
    requiredPermissions: ["consultant_messages.read"],
    riskLevel: "high",
  }),
  staffPage(77, "operations", "inventory", {
    title: "庫存管理",
    description: "管理品項、批號、效期及所有庫存異動。",
    primaryActions: ["入庫", "出庫", "退回", "調整", "個案領用"],
    filters: ["分支", "品項", "批號", "效期狀態", "異動類型"],
    metrics: ["庫存品項", "低庫存", "近效期", "已過期", "待盤點"],
    columns: ["品項", "批號", "效期", "現有量", "安全量", "最近異動", "狀態"],
    acceptance: ["任何異動不得造成負庫存，近效期明確警示且個案領用可追溯指示與人員。"],
    requiredPermissions: ["inventory.read"],
    riskLevel: "sensitive",
  }),
  staffPage(78, "operations", "staff-lab-reports", {
    title: "員工檢驗報告",
    description: "受限管理員工檢驗、結果、效期與證明。",
    primaryActions: ["新增報告", "建立更正", "追加作廢版本"],
    filters: ["分支", "員工", "檢驗類型", "日期", "人工效期", "重複警示", "證明"],
    metrics: ["人工效期內", "即將到期（未設定）", "人工效期已過", "重複警示"],
    columns: ["員工", "檢驗類型", "日期", "院所", "結果文字", "人工有效至", "證明", "重複依據"],
    acceptance: ["同一內容或同員工、檢驗類型、檢驗日與院所相同時列出可解釋警示並保留各筆，不自動合併。結果只由獨立 staff_health 權限及近期同工作階段 AAL2 查閱；人工效期不作醫療判讀，提醒與附件未配置時明示未設定。"],
    requiredPermissions: ["staff_health.read"],
    riskLevel: "high",
  }),
  staffPage(79, "operations", "evaluations", {
    title: "評鑑管理",
    description: "依縣市、年度與版本管理評鑑指標及證據。",
    primaryActions: ["建立評鑑", "上傳證據", "指派負責人", "送出快照"],
    filters: ["縣市", "年度", "版本", "負責人", "狀態"],
    metrics: ["指標數", "已完成", "待補證據", "逾期"],
    columns: ["指標", "縣市／年度", "版本", "負責人", "期限", "證據", "複核", "狀態"],
    acceptance: ["指標不寫死中央版本，送出後形成不可變快照且可追溯每項證據。"],
    riskLevel: "high",
  }),

  staffPage(80, "governance", "central-html-import", {
    origin: "governance",
    title: "中央 HTML 匯入",
    description: "隔離解析、預覽、核准並匯入中央照顧系統 HTML。",
    primaryActions: ["上傳 HTML", "查看解析預覽", "處理衝突", "核准匯入", "重新解析"],
    filters: ["批次狀態", "上傳日期", "上傳者", "個案識別", "映射版本"],
    metrics: ["待解析", "待映射", "驗證失敗", "待核准", "已匯入", "重複"],
    columns: ["批次", "檔案雜湊", "區段數", "映射版本", "衝突數", "上傳者", "狀態"],
    acceptance: ["HTML 靜態解析且外部請求與程式執行皆為零；核准交易失敗時正式資料變更為零。"],
    requiredPermissions: ["imports.manage"],
    riskLevel: "high",
  }),
  staffPage(81, "governance", "roles-data-scopes", {
    origin: "governance",
    title: "角色與資料範圍",
    description: "治理頁面、動作、欄位、組織與個案層級權限。",
    primaryActions: ["建立角色", "調整範圍", "申請擴權", "覆核擴權", "緊急解鎖"],
    filters: ["角色", "分支", "頁面", "權限類型", "有效狀態"],
    metrics: ["有效角色", "待覆核擴權", "即將到期委派", "緊急解鎖"],
    columns: ["角色／人員", "頁面", "動作", "資料範圍", "有效期間", "覆核人", "狀態"],
    acceptance: ["權限擴張須第二人核准，角色×頁面×動作自動測試跨租戶資料外洩為零。"],
    requiredPermissions: ["roles.manage"],
    riskLevel: "high",
  }),
  staffPage(82, "governance", "form-rule-versions", {
    origin: "governance",
    title: "表單與規則版本",
    description: "管理官方及自訂表單、公式、代碼、費率與生效版本。",
    primaryActions: ["建立草稿", "測試規則", "送出覆核", "發布版本", "停用版本"],
    filters: ["類型", "縣市", "年度", "發布狀態", "生效日期"],
    metrics: ["有效版本", "草稿", "待覆核", "即將生效", "重疊警示"],
    columns: ["規則／表單", "類型", "縣市／年度", "版本", "生效期間", "覆核人", "狀態"],
    acceptance: ["發布須雙人核准且生效期間不得重疊，既有紀錄仍顯示並使用原版本。"],
    requiredPermissions: ["forms.manage"],
    riskLevel: "high",
  }),
  staffPage(83, "governance", "integrations-audit", {
    origin: "governance",
    title: "整合與稽核中心",
    description: "追蹤來源資料盤點、缺漏與人工核對版本，查閱整合活動及去敏感稽核事件；正式整合操作仍待配置。",
    primaryActions: ["資料盤點", "修訂盤點", "獨立人工覆核", "查看整合", "搜尋稽核"],
    filters: ["資料類別", "盤點狀態", "整合", "事件類型", "日期", "操作者", "結果", "相關 ID"],
    metrics: ["資料待補件", "盤點待核對", "人工核對完成", "整合事件", "稽核紀錄"],
    columns: ["資料類別／項目", "來源", "資料期間", "缺漏／差異", "負責角色", "版本／覆核", "相關 ID"],
    acceptance: ["所有整合有目的、資料欄位、區域與負責人；機密不得入日誌且失敗可冪等重試。"],
    requiredPermissions: ["audit.view"],
    riskLevel: "high",
  }),
] as const;
